// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { Expr } from "./Expr";
import type { Field } from "./Field";

export type Action = { "kind": "create", collection: string, id: Expr, values: { [key in string]: Expr }, } | { "kind": "update", collection: string, id: Expr, values: { [key in string]: Expr }, } | { "kind": "delete", collection: string, id: Expr, } | { "kind": "set", key: string, value: Expr, } | { "kind": "sequence", actions: Array<Action>, } | { "kind": "parallel", actions: Array<Action>, } | { "kind": "conditional", condition: Expr, yes: Action, no: Action | null, } | { "kind": "navigate", screen: string, } | { "kind": "back" } | { "kind": "open", overlay: string, } | { "kind": "close", overlay: string, } | { "kind": "effect", capability: Capability, input: Expr, } | { "kind": "await_effect", capability: Capability, input: Expr, output: Field, on_success: Action, on_failure: Action, };
