// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { BehaviorTest } from "./BehaviorTest";
import type { Collection } from "./Collection";
import type { Migration } from "./Migration";
import type { Screen } from "./Screen";
import type { Theme } from "./Theme";
import type { Value } from "./Value";

export type Application = { schema_version: number, runtime_features: Array<string>, id: string, revision: string, parent: string | null, title: string, description: string, locale: string, messages: { [key in string]: { [key in string]: string } }, collections: { [key in string]: Collection }, state: { [key in string]: Value }, screens: Array<Screen>, initial_screen: string, actions: { [key in string]: Action }, capabilities: import('./Capability').Capability[], theme: Theme, migrations: Array<Migration>, tests: Array<BehaviorTest>, };
