// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr";
import type { Value } from "./Value";

export type BehaviorTest = { name: string, action: string, event: { [key in string]: Value }, assertion: Expr, };
