// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BinaryOp = "eq" | "ne" | "lt" | "le" | "gt" | "ge" | "add" | "subtract" | "multiply" | "divide" | "and" | "or";
