// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";

export type Collection = { fields: { [key in string]: Field }, indexes: Array<Array<string>>, };
