// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Component = "text" | "heading" | "button" | "icon" | "image" | "stack" | "row" | "grid" | "card" | "divider" | "spacer" | "list" | "table" | "form" | "text_input" | "numeric_input" | "date_input" | "datetime_input" | "checkbox" | "toggle" | "radio" | "select" | "multi_select" | "slider" | "textarea" | "tabs" | "modal" | "drawer" | "alert" | "badge" | "progress" | "stat" | "chart" | "empty_state" | "calendar";
