// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageEvent } from "./StageEvent";
import type { Usage } from "./Usage";

export type CompileMessage = { "kind": "stage", event: StageEvent, } | { "kind": "package", package_base64: string, usage: Usage, } | { "kind": "error", code: string, message: string, };
