// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";

export type DataType = { "type": "string" } | { "type": "boolean" } | { "type": "integer" } | { "type": "decimal", scale: number, } | { "type": "date" } | { "type": "datetime" } | { "type": "duration" } | { "type": "enum", values: Array<string>, } | { "type": "url" } | { "type": "optional", inner: DataType, } | { "type": "list", item: DataType, } | { "type": "map", value: DataType, } | { "type": "record", fields: { [key in string]: Field }, } | { "type": "reference", collection: string, };
