// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { EffectFlow } from "./EffectFlow";
import type { Value } from "./Value";

export type Effect = { id: string, capability: Capability, input: Value, flow?: EffectFlow | null, };
