// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value";

export type Event = { action: string, values: { [key in string]: Value }, now: string, timezone: string, };
