// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryOp } from "./BinaryOp";
import type { ContextKey } from "./ContextKey";
import type { Value } from "./Value";

export type Expr = { "op": "literal", value: Value, } | { "op": "event", key: string, } | { "op": "state", key: string, } | { "op": "item", field: string, } | { "op": "collection", name: string, } | { "op": "binary", operator: BinaryOp, left: Expr, right: Expr, } | { "op": "not", value: Expr, } | { "op": "if", condition: Expr, yes: Expr, no: Expr, } | { "op": "length", value: Expr, } | { "op": "concat", values: Array<Expr>, } | { "op": "filter", collection: Expr, predicate: Expr, } | { "op": "map", collection: Expr, value: Expr, } | { "op": "sort", collection: Expr, field: string, descending: boolean, } | { "op": "sum", collection: Expr, field: string, } | { "op": "coalesce", values: Array<Expr>, } | { "op": "context", key: ContextKey, };
