// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";
import type { Expr } from "./Expr";
import type { Value } from "./Value";

export type Field = { data_type: DataType, default: Value | null, max_length: number | null, minimum: string | null, maximum: string | null, derived: Expr | null, };
