// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Impact = { operation: string, collection: string, field: string | null, previous_field: string | null, affected_records: number, destructive: boolean, };
