// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Impact } from "./Impact";

export type MigrationReport = { from_revision: string, to_revision: string, requires_confirmation: boolean, impacts: Array<Impact>, };
