// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationOp } from "./MigrationOp";

export type Migration = { from_revision: string, operations: Array<MigrationOp>, };
