// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from "./Expr";
import type { Value } from "./Value";

export type MigrationOp = { "kind": "add_field", collection: string, field: string, default: Value, } | { "kind": "rename_field", collection: string, from: string, to: string, } | { "kind": "remove_field", collection: string, field: string, } | { "kind": "add_collection", name: string, } | { "kind": "remove_collection", name: string, } | { "kind": "transform", collection: string, field: string, value: Expr, };
