// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Component } from "./Component";
import type { Expr } from "./Expr";
import type { Style } from "./Style";

export type Node = { id: string, kind: Component, text: Expr | null, collection: string | null, field: string | null, action: string | null, options: Array<string>, children: Array<Node>, style: Style, };
