// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

export type ProviderInfo = { fixture: boolean, kind: Kind, model: string, endpoint: string, credential_owner: string, signing_authority: string, max_cost_microusd: number, input_microusd_per_million: number | null, output_microusd_per_million: number | null, };
