// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Raster = { digest: string, media_type: string, bytes_hex: string, width: number, height: number, };
