// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { MigrationReport } from "./MigrationReport";

export type RevisionReport = { review_digest: string, source_package: string, target_package: string, migration: MigrationReport, permissions_added: Array<Capability>, permissions_removed: Array<Capability>, };
