// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Usage } from "./Usage";

export type StageEvent = { stage: string, attempt: number, elapsed_ms: number, usage: Usage, };
