// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value";

export type State = { revision: string, values: { [key in string]: Value }, collections: { [key in string]: { [key in string]: { [key in string]: Value } } }, };
