// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Size } from "./Size";
import type { Tone } from "./Tone";

export type Style = { tone: Tone, size: Size, };
