// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Accent } from "./Accent";
import type { Density } from "./Density";
import type { Radius } from "./Radius";

export type Theme = { accent: Accent, density: Density, radius: Radius, };
