// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decimal } from "./Decimal";
import type { Reference } from "./Reference";

export type Value = { "type": "null" } | { "type": "string", "value": string } | { "type": "boolean", "value": boolean } | { "type": "integer", "value": string } | { "type": "decimal", "value": Decimal } | { "type": "date", "value": string } | { "type": "datetime", "value": string } | { "type": "duration", "value": string } | { "type": "list", "value": Array<Value> } | { "type": "map", "value": { [key in string]: Value } } | { "type": "reference", "value": Reference };
