// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Component } from "./Component";
import type { Field } from "./Field";
import type { Style } from "./Style";
import type { Value } from "./Value";

export type ViewNode = { id: string, kind: Component, text: string, value: Value | null, input_contract: Field | null, form_scope: string | null, disabled: boolean, field: string | null, action: string | null, event_fields: Array<string> | null, record: string | null, options: Array<string>, style: Style, open: boolean, active_overlay: boolean, children: Array<ViewNode>, };
