import {test,expect} from './fixtures';
import AxeBuilder from '@axe-core/playwright';
import type {Page,TestInfo} from '@playwright/test';
async function audit(page:Page,info:TestInfo,label:string){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();await info.attach(label,{body:JSON.stringify(result),contentType:'application/json'});expect(result.violations.map(rule=>({id:rule.id,impact:rule.impact,help:rule.help,nodes:rule.nodes.map(node=>({target:node.target,summary:node.failureSummary}))}))).toEqual([]);}
test('consumer pages and the signed visual application have no detected accessibility violations',async({page},info)=>{
  for(const path of ['/','/registry','/generation','/account','/operations']){await page.goto(path);await expect(page.locator('#main')).toBeVisible();await audit(page,info,path==='/'?'local':'page-'+path.slice(1));}
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/visuals.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();await expect(page.frameLocator('iframe').getByRole('heading',{name:'Visual components',exact:true})).toBeVisible();await audit(page,info,'signed-profile');await page.frameLocator('iframe').getByRole('tab',{name:'Overview',exact:true}).click();await expect(page.frameLocator('iframe').getByRole('img',{name:'Verified checker sample',exact:true})).toBeVisible();await audit(page,info,'signed-visuals');await page.setViewportSize({width:360,height:800});await audit(page,info,'signed-visuals-narrow');const calendar=page.frameLocator('iframe').getByRole('region',{name:'October plans calendar',exact:true});await calendar.focus();await calendar.press('ArrowRight');await expect.poll(()=>calendar.evaluate(element=>element.scrollLeft)).toBeGreaterThan(0);await page.emulateMedia({colorScheme:'dark'});await audit(page,info,'signed-visuals-dark');const screenshot=info.outputPath('calendar-narrow-dark.png');await calendar.screenshot({path:screenshot});await info.attach('calendar-narrow-dark',{path:screenshot,contentType:'image/png'});await page.goto('/');await audit(page,info,'local-dark');
});
test('trusted modal and drawer focus scopes have no detected accessibility violations',async({page},info)=>{
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/runtime.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');await audit(page,info,'controls-home');await page.emulateMedia({colorScheme:'dark'});await audit(page,info,'controls-home-dark');await frame.getByRole('button',{name:'Show dialog',exact:true}).click();await expect(frame.getByRole('dialog')).toBeVisible();await audit(page,info,'modal');await frame.getByRole('dialog').press('Escape');await frame.getByRole('button',{name:'Show drawer',exact:true}).click();await expect(frame.getByRole('dialog')).toBeVisible();await audit(page,info,'drawer');
});
