import {test,expect} from './fixtures';
import {readFileSync} from 'node:fs';
import AxeBuilder from '@axe-core/playwright';
test('encrypted typed effects durably retain unknown outcomes and commit validated callbacks once',async({page})=>{
  await page.goto('/');const bytes=[...readFileSync('artifacts/controls/encrypted-effects.need')];
  const result=await page.evaluate(async bytes=>{
    const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});
    const {openVaultStore}=await import('/vault-store.js'),{DurableSyncSession}=await import('/sync-journal.js');
    const account=crypto.randomUUID(),vault=new wasm.BrowserVault(account),store=await openVaultStore(),packageBytes=new Uint8Array(bytes),scope=JSON.stringify({values:[],collections:['habits']}),original=vault.start_document(packageBytes,crypto.randomUUID(),scope,1,true),document=JSON.parse(original.binding()).document.document,backup=vault.local_backup();await store.save(account,backup,null);backup.fill(0);
    let journal=await DurableSyncSession.create(store.documents,vault,packageBytes,original,{account,rootGeneration:1,scope,ownerEpoch:1,authority:vault.account_authority(),roster:JSON.stringify([JSON.parse(original.membership())])});
    const request=()=>journal.dispatch(JSON.stringify({action:'copy',values:{name:{type:'string',value:'Retained clipboard text'}},now:'2026-10-05T00:00:00.000Z',timezone:'UTC'}));
    const before=journal.snapshot(),queue=JSON.stringify(journal.pending());await request();let id=journal.effectReview().id;
    const prepared=journal.effectReview().status==='prepared'&&journal.snapshot()===before&&JSON.stringify(journal.pending())===queue;
    const foreign=vault.start_document(packageBytes,crypto.randomUUID(),scope,1,true);let crossDocumentRejected=false;try{foreign.restore_effect_checkpoint(journal.effectReview().checkpoint);}catch{crossDocumentRejected=true;}foreign.free();
    const save=store.documents.save.bind(store.documents);store.documents.save=async()=>{throw Error('Injected intent failure');};let failedBegin=false;try{await journal.beginEffect(id);}catch{failedBegin=true;}store.documents.save=save;
    const unchangedBegin=journal.effectReview().status==='prepared';await journal.beginEffect(id);await journal.close();journal=await DurableSyncSession.open(store.documents,vault,account,document,true);let replayRejected=false;try{await journal.beginEffect(id);}catch{replayRejected=true;}
    store.documents.save=async()=>{throw Error('Injected returned-result failure');};let failedRecord=false;try{await journal.recordEffectResult(id,{status:'success',value:{type:'boolean',value:true}});}catch{failedRecord=true;}store.documents.save=save;const retainedDispatching=journal.effectReview().status==='dispatching'&&journal.snapshot()===before;
    await journal.recordEffectResult(id,{status:'success',value:{type:'boolean',value:true}});let invalidResult=false;try{await journal.finishEffect(id);}catch{invalidResult=true;}const retainedInvalid=journal.snapshot()===before&&journal.effectReview().status==='result';await journal.discardEffect(id);
    await request();id=journal.effectReview().id;await journal.beginEffect(id);await journal.recordEffectResult(id,{status:'success',value:{type:'string',value:'Applied clipboard text'}});
    store.documents.save=async()=>{throw Error('Injected completion failure');};let failedFinish=false;try{await journal.finishEffect(id);}catch{failedFinish=true;}store.documents.save=save;
    const unchangedFinish=journal.snapshot()===before&&journal.effectReview().status==='result';await journal.close();journal=await DurableSyncSession.open(store.documents,vault,account,document,true);await journal.finishEffect(id);let duplicateRejected=false;try{await journal.finishEffect(id);}catch{duplicateRejected=true;}
    const completed=JSON.parse(journal.snapshot()).values.name.value==='Applied clipboard text'&&!journal.effectReview();
    await request();id=journal.effectReview().id;await journal.beginEffect(id);await journal.dispatch(JSON.stringify({action:'change_name',values:{},now:'2026-10-05T00:00:00.000Z',timezone:'UTC'}));const newer=journal.snapshot();await journal.recordEffectResult(id,{status:'success',value:{type:'string',value:'Must not overwrite newer state'}});let staleRejected=false;try{await journal.finishEffect(id);}catch{staleRejected=true;}
    await journal.close();journal=await DurableSyncSession.open(store.documents,vault,account,document,true);const coldReview=journal.effectReview().stale&&journal.effectReview().outcome.value.value==='Must not overwrite newer state'&&journal.snapshot()===newer;
    await journal.discardEffect(id);const reviewed=journal.snapshot()===newer&&!journal.effectReview();await journal.close();vault.free();store.close();return {prepared,crossDocumentRejected,failedBegin,unchangedBegin,replayRejected,failedRecord,retainedDispatching,invalidResult,retainedInvalid,failedFinish,unchangedFinish,duplicateRejected,completed,staleRejected,coldReview,reviewed};
  },bytes);
  expect(result).toEqual({prepared:true,crossDocumentRejected:true,failedBegin:true,unchangedBegin:true,replayRejected:true,failedRecord:true,retainedDispatching:true,invalidResult:true,retainedInvalid:true,failedFinish:true,unchangedFinish:true,duplicateRejected:true,completed:true,staleRejected:true,coldReview:true,reviewed:true});
});
test('trusted shell requires a separate fresh clipboard click and retains unresolved actions after reload',async({page})=>{
  await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).__clipboardWrites=[...((window as any).__clipboardWrites??[]),text];}}});});
  await page.addInitScript(()=>{const send=Worker.prototype.postMessage;Worker.prototype.postMessage=function(value:any,...rest:any[]){if(value?.command?.kind==='record-effect'&&(window as any).__failRecordResult){queueMicrotask(()=>this.dispatchEvent(new MessageEvent('message',{data:{id:value.id,ok:false,error:'Injected result persistence unavailable'}})));return;}return (send as any).call(this,value,...rest);};});
  await page.goto('/');const account=await page.evaluate(async()=>{const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const {openVaultStore}=await import('/vault-store.js'),account=crypto.randomUUID(),vault=new wasm.BrowserVault(account),store=await openVaultStore(),backup=vault.local_backup();try{await store.save(account,backup,null);return account;}finally{backup.fill(0);vault.free();store.close();}});
  await page.goto(`/encrypted#account=${account}`);await expect(page.getByText('Encrypted browser storage ready',{exact:true})).toBeVisible();await page.getByLabel('Import encrypted-library application').setInputFiles('artifacts/controls/encrypted-effects.need');await page.getByRole('button',{name:'Trust signer and save encrypted application',exact:true}).click();
  const frame=page.frameLocator('iframe'),review=page.getByRole('region',{name:'External action review'});await frame.getByLabel('Text to copy',{exact:true}).fill('Reviewed private clipboard text');await frame.getByRole('button',{name:'Request clipboard copy',exact:true}).click();await expect(review.getByLabel('Clipboard content')).toHaveValue('Reviewed private clipboard text');expect(await page.evaluate(()=>(window as any).__clipboardWrites??[])).toEqual([]);
  await review.getByRole('button',{name:'Authorize clipboard write',exact:true}).click();await expect(review.getByRole('button',{name:'Copy reviewed text',exact:true})).toBeEnabled();expect(await page.evaluate(()=>(window as any).__clipboardWrites??[])).toEqual([]);await page.evaluate(()=>(window as any).__failRecordResult=true);await review.getByRole('button',{name:'Copy reviewed text',exact:true}).click();await expect(review.getByRole('alert')).toContainText('Injected result persistence unavailable');await expect(review.getByLabel('Retained external result')).toHaveValue(/Reviewed private clipboard text/);
  let guarded=false;page.once('dialog',async dialog=>{guarded=dialog.message().includes('returned external result is only retained on this page');await dialog.dismiss();});await page.getByRole('button',{name:'Delete encrypted application',exact:true}).click();expect(guarded).toBe(true);await expect(review.getByLabel('Retained external result')).toHaveValue(/Reviewed private clipboard text/);await expect(review.getByRole('button',{name:'Copy reviewed text',exact:true})).toHaveCount(0);
  const download=page.waitForEvent('download');page.once('dialog',dialog=>dialog.accept());await review.getByRole('button',{name:'Export plaintext retained action',exact:true}).click();const stream=await(await download).createReadStream();let exported='';for await(const chunk of stream!)exported+=chunk.toString();expect(JSON.parse(exported).outcome.value.value).toBe('Reviewed private clipboard text');expect(JSON.parse(exported).state).toBeUndefined();
  await page.evaluate(()=>(window as any).__failRecordResult=false);await review.getByRole('button',{name:'Save and apply retained result',exact:true}).click();await expect(review).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__clipboardWrites)).toEqual(['Reviewed private clipboard text']);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Reviewed private clipboard text');
  await frame.getByLabel('Text to copy',{exact:true}).fill('Unknown outcome text');await frame.getByRole('button',{name:'Request clipboard copy',exact:true}).click();await review.getByRole('button',{name:'Authorize clipboard write',exact:true}).click();await expect(review.getByRole('button',{name:'Copy reviewed text',exact:true})).toBeEnabled();page.once('dialog',dialog=>dialog.accept());await page.reload();await page.getByRole('button',{name:'Open Encrypted effects fixture',exact:true}).click();await expect(review.getByRole('status')).toContainText('The external outcome is unknown');await expect(review.getByRole('button',{name:'Copy reviewed text',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__clipboardWrites??[])).toEqual([]);
  const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();expect(audit.violations).toEqual([]);
});

test('a denied clipboard operation commits only its validated failure callback without replay',async({page})=>{
  await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{(window as any).__deniedWrites=((window as any).__deniedWrites??0)+1;throw new DOMException('Denied','NotAllowedError');}}});});
  await page.goto('/');const account=await page.evaluate(async()=>{const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const {openVaultStore}=await import('/vault-store.js'),account=crypto.randomUUID(),vault=new wasm.BrowserVault(account),store=await openVaultStore(),backup=vault.local_backup();try{await store.save(account,backup,null);return account;}finally{backup.fill(0);vault.free();store.close();}});
  await page.goto(`/encrypted#account=${account}`);await expect(page.getByText('Encrypted browser storage ready',{exact:true})).toBeVisible();await page.getByLabel('Import encrypted-library application').setInputFiles('artifacts/controls/encrypted-effects.need');await page.getByRole('button',{name:'Trust signer and save encrypted application',exact:true}).click();
  const frame=page.frameLocator('iframe'),review=page.getByRole('region',{name:'External action review'});await frame.getByLabel('Text to copy',{exact:true}).fill('Denied private clipboard text');await frame.getByRole('button',{name:'Request clipboard copy',exact:true}).click();await review.getByRole('button',{name:'Authorize clipboard write',exact:true}).click();await review.getByRole('button',{name:'Copy reviewed text',exact:true}).click();await expect(review).toHaveCount(0);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('clipboard_denied');expect(await page.evaluate(()=>(window as any).__deniedWrites)).toBe(1);
  page.once('dialog',dialog=>dialog.accept());await page.reload();await page.getByRole('button',{name:'Open Encrypted effects fixture',exact:true}).click();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('clipboard_denied');await expect(review).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__deniedWrites??0)).toBe(0);
});
