import {test,expect} from './fixtures';
import {readFileSync} from 'node:fs';
import AxeBuilder from '@axe-core/playwright';
async function vault(page:import('@playwright/test').Page){return page.evaluate(async()=>{const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const {openVaultStore}=await import('/vault-store.js'),account=crypto.randomUUID(),vault=new wasm.BrowserVault(account),store=await openVaultStore(),bytes=vault.local_backup();try{await store.save(account,bytes,null);return account;}finally{bytes.fill(0);vault.free();store.close();}});}
test('encrypted raw drafts survive cold reopen and require review before application data changes',async({page})=>{
  let leaked=false;page.on('request',request=>{if(request.postData()?.includes('Private raw recovery'))leaked=true;});
  await page.goto('/');const account=await vault(page);await page.goto(`/encrypted#account=${account}`);await expect(page.getByText('Encrypted browser storage ready',{exact:true})).toBeVisible();await page.getByLabel('Import encrypted-library application').setInputFiles('artifacts/controls/encrypted-widgets.need');await page.getByRole('button',{name:'Trust signer and save encrypted application',exact:true}).click();const frame=page.frameLocator('iframe'),recovery=page.getByRole('region',{name:'Encrypted draft recovery'});
  await frame.getByLabel('Name',{exact:true}).fill('Private raw recovery');await frame.getByLabel('Amount',{exact:true}).fill('1.234');await expect(recovery.getByRole('status')).toContainText('Encrypted recovery saved on this browser');await expect(recovery.getByText('2 inputs',{exact:false})).toBeVisible();await expect(page.getByText('Encrypted browser storage · 0 pending changes',{exact:true})).toBeVisible();
  page.once('dialog',dialog=>dialog.accept());await page.reload();await page.getByRole('button',{name:'Open Encrypted widgets fixture',exact:true}).click();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Original');await expect(recovery.getByRole('button',{name:'Review encrypted recovery',exact:true})).toBeEnabled();
  page.once('dialog',dialog=>dialog.accept());await recovery.getByRole('button',{name:'Review encrypted recovery',exact:true}).click();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private raw recovery');await expect(frame.getByLabel('Amount',{exact:true})).toHaveValue('1.234');await expect(frame.getByRole('alert').filter({hasText:'Use at most 2 decimal places'})).toBeVisible();
  await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(frame.getByRole('region',{name:'Review changed Name',exact:true})).toBeVisible();await frame.getByRole('region',{name:'Review changed Name',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('region',{name:'Review changed Amount',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByLabel('Amount',{exact:true}).fill('1.23');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(recovery.getByRole('status')).toContainText('Encrypted recovery saved on this browser');await expect(page.getByText('Encrypted browser storage · 0 pending changes',{exact:true})).toBeVisible();
  expect(leaked).toBe(false);const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();expect(audit.violations).toEqual([]);await page.reload();await page.getByRole('button',{name:'Open Encrypted widgets fixture',exact:true}).click();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private raw recovery');await expect(frame.getByLabel('Amount',{exact:true})).toHaveValue('1.23');
});
test('private draft journals preserve originals under failed writes, stale deletion, bounds and cold decryption',async({page})=>{
  await page.goto('/');const bytes=[...readFileSync('artifacts/controls/encrypted-widgets.need')];
  const result=await page.evaluate(async bytes=>{
    const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const {openVaultStore}=await import('/vault-store.js'),{DurableSyncSession}=await import('/sync-journal.js');const account=crypto.randomUUID(),vault=new wasm.BrowserVault(account),store=await openVaultStore(),packageBytes=new Uint8Array(bytes),scope=JSON.stringify({values:[],collections:['habits']}),original=vault.start_document(packageBytes,crypto.randomUUID(),scope,1,true),document=JSON.parse(original.binding()).document.document,digest=JSON.parse(wasm.inspect_package(packageBytes)).digest,backup=vault.local_backup();await store.save(account,backup,null);backup.fill(0);
    let journal=await DurableSyncSession.create(store.documents,vault,packageBytes,original,{account,rootGeneration:1,scope,ownerEpoch:1,authority:vault.account_authority(),roster:JSON.stringify([JSON.parse(original.membership())])});const writer=crypto.randomUUID(),fields=[{scope:'profile',field:'name',id:'name',raw:'Private unsaved sentinel'},{scope:'profile',field:'amount',id:'amount',raw:'1.234'}],state=journal.snapshot(),queue=JSON.stringify(journal.pending());await journal.saveDrafts(writer,digest,fields);const summary=journal.draftSummaries()[0];
    const persisted=await store.documents.load(account,document),parsed=JSON.parse(new TextDecoder().decode(persisted.bytes));persisted.bytes.fill(0);const exact=JSON.stringify(parsed.drafts[0].fields)===JSON.stringify(fields),initialView=journal.view(),save=store.documents.save;store.documents.save=async()=>{throw Error('Injected draft persistence failure');};let failed=false;try{await journal.saveDrafts(writer,digest,[{...fields[0],raw:'Must remain only in memory'}]);}catch{failed=true;}finally{store.documents.save=save;}const failureAtomic=journal.view()===initialView&&JSON.stringify(journal.loadDraft(0,writer,1).fields)===JSON.stringify(fields);
    let revisionRejected=false,malformedRejected=false;try{await journal.saveDrafts(writer,'0'.repeat(64),fields);}catch{revisionRejected=true;}try{await journal.saveDrafts(writer,digest,[fields[0],fields[0]]);}catch{malformedRejected=true;}
    await journal.saveDrafts(writer,digest,[{...fields[0],raw:'Latest private sentinel'}]);let staleDelete=false;try{await journal.forgetDraft(writer,summary.generation);}catch{staleDelete=true;}
    for(let index=1;index<8;index++)await journal.saveDrafts(crypto.randomUUID(),digest,[{...fields[0],raw:`Separate editing session ${index}`}]);let fullRejected=false;try{await journal.saveDrafts(crypto.randomUUID(),digest,fields);}catch{fullRejected=true;}const retained=journal.draftSummaries().length===8;await journal.close();journal=await DurableSyncSession.open(store.documents,vault,account,document,true);const cold=journal.loadDraft(0,writer,2).fields[0].raw==='Latest private sentinel',unchanged=journal.snapshot()===state&&JSON.stringify(journal.pending())===queue;await journal.forgetDraft(writer,2);const removed=journal.draftSummaries().length===7;const last=await store.documents.load(account,document);last.bytes.fill(0);await store.documents.remove(account,document,last.generation,last.rootGeneration);let resurrectionRejected=false;try{await journal.saveDrafts(crypto.randomUUID(),digest,fields);}catch{resurrectionRejected=true;}const deleted=await store.documents.load(account,document)===undefined;await journal.close();vault.free();store.close();return {exact,failed,failureAtomic,revisionRejected,malformedRejected,staleDelete,fullRejected,retained,cold,unchanged,removed,resurrectionRejected,deleted};
  },bytes);expect(result).toEqual({exact:true,failed:true,failureAtomic:true,revisionRejected:true,malformedRejected:true,staleDelete:true,fullRejected:true,retained:true,cold:true,unchanged:true,removed:true,resurrectionRejected:true,deleted:true});
});

test('an unversioned older renderer cannot falsely confirm encrypted autosave',async({page})=>{
  await page.addInitScript(()=>{const send=MessagePort.prototype.postMessage;MessagePort.prototype.postMessage=function(value:any,...rest:any[]){if(value?.kind==='needware-draft-status'){value={...value};delete value.version;}return (send as any).call(this,value,...rest);};});
  await page.goto('/');const account=await vault(page);await page.goto(`/encrypted#account=${account}`);await expect(page.getByText('Encrypted browser storage ready',{exact:true})).toBeVisible();await page.getByLabel('Import encrypted-library application').setInputFiles('artifacts/controls/encrypted-widgets.need');await page.getByRole('button',{name:'Trust signer and save encrypted application',exact:true}).click();const frame=page.frameLocator('iframe'),recovery=page.getByRole('region',{name:'Encrypted draft recovery'});await frame.getByLabel('Name',{exact:true}).fill('Legacy raw input retained');await expect(recovery.getByRole('status')).toContainText('Encrypted recovery requires the current runtime');await recovery.getByRole('button',{name:'Refresh encrypted recoveries',exact:true}).click();await expect(recovery.getByRole('button',{name:'Review encrypted recovery',exact:true})).toHaveCount(0);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Legacy raw input retained');
  const download=page.waitForEvent('download');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Export plaintext unsaved inputs',exact:true}).click();const stream=await(await download).createReadStream();let raw='';for await(const chunk of stream!)raw+=chunk.toString();expect(JSON.parse(raw).drafts[0].raw).toBe('Legacy raw input retained');
});
