import {test,expect} from './fixtures';
import {readFileSync} from 'node:fs';
import type {Page} from '@playwright/test';
async function backend(page:Page,kind:'default'|'indexeddb'){
  await page.goto('/registry');if(kind==='indexeddb')await page.evaluate(async()=>{await new Promise<void>((resolve,reject)=>{const request=indexedDB.open('needware-storage-choice-1',1);request.onupgradeneeded=()=>request.result.createObjectStore('settings');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('settings','readwrite');tx.objectStore('settings').put('indexeddb','backend');tx.oncomplete=()=>{db.close();resolve();};tx.onabort=()=>reject(tx.error);};});});
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();
}
for(const kind of ['default','indexeddb'] as const){
  test(`local effect ${kind} cold reopen and writer conflicts retain one-shot results`,async({page})=>{
    await backend(page,kind);const bytes=[...readFileSync('artifacts/controls/local-effects.need')];
    const result=await page.evaluate(async bytes=>{
      function client(){const worker=new Worker('/runtime-worker.js',{type:'module'});let id=0;const pending=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void}>();worker.onmessage=e=>{const entry=pending.get(e.data.id);if(!entry)return;pending.delete(e.data.id);if(e.data.ok)entry.resolve(e.data.data);else entry.reject(Error(e.data.error));};return {send:(command:any)=>new Promise<any>((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});worker.postMessage({id:next,command});}),close:()=>worker.terminate()};}
      const a=client(),packageBytes=new Uint8Array(bytes);let loaded=await a.send({kind:'load',bytes:packageBytes,consent:true}),instance=loaded.instance;
      await a.send({kind:'dispatch',instance,action:'copy',values:{name:{type:'string',value:'Durable local request'}}});const source=await a.send({kind:'effect-review',instance}),before=await a.send({kind:'export-state'});
      const b=client();loaded=await b.send({kind:'load',bytes:packageBytes,consent:true});let conflict=false;try{await a.send({kind:'begin-effect',instance,id:source.id});}catch{conflict=true;}const retained=(await a.send({kind:'effect-review',instance})).status==='prepared'&&(await a.send({kind:'export-state'}))===before;a.close();
      instance=loaded.instance;await b.send({kind:'begin-effect',instance,id:source.id});b.close();const c=client();loaded=await c.send({kind:'load',bytes:packageBytes,consent:true});instance=loaded.instance;let replay=false;try{await c.send({kind:'begin-effect',instance,id:source.id});}catch{replay=true;}
      await c.send({kind:'record-effect',instance,id:source.id,outcome:{status:'success',value:{type:'string',value:'Validated local result'}}});c.close();const d=client();loaded=await d.send({kind:'load',bytes:packageBytes,consent:true});instance=loaded.instance;const e=client(),fresh=await e.send({kind:'load',bytes:packageBytes,consent:true});let completionConflict=false;try{await d.send({kind:'finish-effect',instance,id:source.id});}catch{completionConflict=true;}const retainedResult=(await d.send({kind:'effect-review',instance})).status==='result'&&(await d.send({kind:'export-state'}))===before;d.close();instance=fresh.instance;await e.send({kind:'finish-effect',instance,id:source.id});const completed=JSON.parse(await e.send({kind:'export-state'})).values.name.value==='Validated local result'&&(await e.send({kind:'effect-review',instance}))===null;let duplicate=false;try{await e.send({kind:'finish-effect',instance,id:source.id});}catch{duplicate=true;}const storage=fresh.storage;e.close();return {conflict,retained,replay,completionConflict,retainedResult,completed,duplicate,storage};
    },bytes);expect(result.conflict).toBe(true);expect(result.retained).toBe(true);expect(result.replay).toBe(true);expect(result.completionConflict).toBe(true);expect(result.retainedResult).toBe(true);expect(result.completed).toBe(true);expect(result.duplicate).toBe(true);if(kind==='indexeddb')expect(result.storage).toContain('IndexedDB');else expect(result.storage).toMatch(/SQLite|IndexedDB/);
  });
  test(`local effect ${kind} rollback cannot revive historical prepared or dispatched intents`,async({page})=>{
    await backend(page,kind);const source=[...readFileSync('artifacts/controls/local-effects.need')],revised=[...readFileSync('artifacts/controls/local-effects-revised.need')];
    const result=await page.evaluate(async({source,revised})=>{
      const worker=new Worker('/runtime-worker.js',{type:'module'});let serial=0;const waiting=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void}>();worker.onmessage=e=>{const call=waiting.get(e.data.id);if(!call)return;waiting.delete(e.data.id);e.data.ok?call.resolve(e.data.data):call.reject(Error(e.data.error));};const send=(command:any)=>new Promise<any>((resolve,reject)=>{const id=++serial;waiting.set(id,{resolve,reject});worker.postMessage({id,command});});
      const bytes=new Uint8Array(source),target=new Uint8Array(revised);let loaded=await send({kind:'load',bytes,consent:true}),instance=loaded.instance;const id=loaded.info.application.id;
      const request=async()=>{await send({kind:'dispatch',instance,action:'copy',values:{name:{type:'string',value:'Historical request'}}});return send({kind:'effect-review',instance});};
      const migrate=async()=>{const report=await send({kind:'preview-revision',bytes:target,consent:true});loaded=await send({kind:'activate-revision',review:report.review_digest,destructive:true,permissions:true});instance=loaded.instance;};
      const entry=async()=>(await send({kind:'library'})).find((entry:any)=>entry.id===id);
      const rollback=async(snapshot:number)=>{loaded=await send({kind:'rollback',id,snapshot,expected:(await entry()).generation,consent:true});instance=loaded.instance;};
      const prepared=await request(),snapshot=(await entry()).generation;await migrate();const stale=(await send({kind:'effect-review',instance})).stale;await send({kind:'discard-effect',instance,id:prepared.id});await rollback(snapshot);const cancelledNotRevived=(await send({kind:'effect-review',instance}))===null;let cancelledRejected=false;try{await send({kind:'begin-effect',instance,id:prepared.id});}catch{cancelledRejected=true;}
      const dispatched=await request();await send({kind:'begin-effect',instance,id:dispatched.id});const dispatchedSnapshot=(await entry()).generation;await migrate();await rollback(dispatchedSnapshot);let dispatchedRejected=false;try{await send({kind:'begin-effect',instance,id:dispatched.id});}catch{dispatchedRejected=true;}
      await send({kind:'record-effect',instance,id:dispatched.id,outcome:{status:'success',value:{type:'string',value:'Current retained outcome'}}});await send({kind:'finish-effect',instance,id:dispatched.id});const firstApplied=JSON.parse(await send({kind:'export-state'})).values.name.value==='Current retained outcome';await migrate();await rollback(dispatchedSnapshot);const completedNotRevived=(await send({kind:'effect-review',instance}))===null;let completedRejected=false;try{await send({kind:'begin-effect',instance,id:dispatched.id});}catch{completedRejected=true;}worker.terminate();return {stale,cancelledNotRevived,cancelledRejected,dispatchedRejected,firstApplied,completedNotRevived,completedRejected};
    },{source,revised});expect(result).toEqual({stale:true,cancelledNotRevived:true,cancelledRejected:true,dispatchedRejected:true,firstApplied:true,completedNotRevived:true,completedRejected:true});
  });
}
test('local trusted shell writes only on a fresh reviewed click and never replays after reopening',async({page})=>{
  await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).__localCopies=[...((window as any).__localCopies??[]),text];}}});});
  await backend(page,'default');await page.getByLabel('Import .need',{exact:true}).setInputFiles('artifacts/controls/local-effects.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe'),review=page.getByRole('region',{name:'External action review'});
  await frame.getByLabel('Text to copy',{exact:true}).fill('Reviewed local clipboard text');await frame.getByRole('button',{name:'Request clipboard copy',exact:true}).click();await expect(review.getByLabel('Clipboard content')).toHaveValue('Reviewed local clipboard text');expect(await page.evaluate(()=>(window as any).__localCopies??[])).toEqual([]);await review.getByRole('button',{name:'Authorize clipboard write',exact:true}).click();expect(await page.evaluate(()=>(window as any).__localCopies??[])).toEqual([]);await review.getByRole('button',{name:'Copy reviewed text',exact:true}).click();await expect(review).toHaveCount(0);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Reviewed local clipboard text');expect(await page.evaluate(()=>(window as any).__localCopies)).toEqual(['Reviewed local clipboard text']);
  await frame.getByLabel('Text to copy',{exact:true}).fill('Unknown local outcome');await frame.getByRole('button',{name:'Request clipboard copy',exact:true}).click();await review.getByRole('button',{name:'Authorize clipboard write',exact:true}).click();await expect(review.getByRole('button',{name:'Copy reviewed text',exact:true})).toBeEnabled();page.once('dialog',dialog=>dialog.accept());await page.reload();await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Open Local effects fixture',exact:true}).click();await expect(review.getByRole('status')).toContainText('The external outcome is unknown');await expect(review.getByRole('button',{name:'Copy reviewed text',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>(window as any).__localCopies??[])).toEqual([]);
});
test.describe('legacy local SQLite preservation',()=>{
  test.use({serviceWorkers:'block'});
  test('legacy SQLite upgrades preserve data atomically; unavailable OPFS uses explicit fallback',async({page})=>{
    await page.goto('/registry');await page.route('**/__legacy-local-worker.js',route=>route.fulfill({path:'artifacts/local-storage/legacy-worker.js',contentType:'text/javascript'}));const bytes=[...readFileSync('artifacts/controls/widgets.need')];
    const seed=await page.evaluate(async bytes=>{const worker=new Worker('/__legacy-local-worker.js',{type:'module'});try{return await new Promise<any>((resolve,reject)=>{worker.onmessage=e=>resolve(e.data);worker.onerror=e=>reject(Error(e.message));worker.postMessage(bytes);});}finally{worker.terminate();}},bytes);if(!seed.ok&&seed.stage==='opfs-root'){
      const fallback=await page.evaluate(async()=>{const worker=new Worker('/runtime-worker.js',{type:'module'});try{return await new Promise<any>((resolve,reject)=>{worker.onmessage=e=>resolve(e.data);worker.onerror=e=>reject(Error(e.message));worker.postMessage({id:1,command:{kind:'library'}});});}finally{worker.terminate();}});
      expect(fallback.ok,fallback.error).toBe(true);expect(fallback.data).toEqual([]);const choice=await page.evaluate(async()=>new Promise<string>((resolve,reject)=>{const open=indexedDB.open('needware-storage-choice-1',1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,read=db.transaction('settings').objectStore('settings').get('backend');read.onerror=()=>reject(read.error);read.onsuccess=()=>{db.close();resolve(read.result);};};}));expect(choice).toBe('indexeddb');return;
    }expect(seed.ok,seed.error).toBe(true);
    await page.route('**/__fault-local-worker.js',route=>route.fulfill({path:'artifacts/local-storage/fault-worker.js',contentType:'text/javascript'}));const result=await page.evaluate(async id=>{
      async function request(path:string,command:any){const worker=new Worker(path,{type:'module'});try{return await new Promise<any>((resolve,reject)=>{worker.onmessage=e=>resolve(e.data);worker.onerror=e=>reject(Error(e.message));worker.postMessage({id:1,command});});}finally{worker.terminate();}}
      const failed=await request('/__fault-local-worker.js',{kind:'library'});const library=await request('/runtime-worker.js',{kind:'library'}),history=await request('/runtime-worker.js',{kind:'history',id});return {failed,library,history};
    },seed.id);expect(result.failed.ok).toBe(false);expect(result.failed.error).toContain('Injected effect schema upgrade failure');expect(result.failed.error).toContain('existing data was preserved');expect(result.library.ok).toBe(true);expect(result.library.data).toHaveLength(1);expect(JSON.parse(result.library.data[0].state).values.name.value).toBe('Legacy private state');expect(result.library.data[0].generation).toBe(8);expect(result.history.ok).toBe(true);expect(result.history.data).toHaveLength(1);expect(JSON.parse(result.history.data[0].state).values.name.value).toBe('Legacy archived state');expect(result.history.data[0].generation).toBe(7);
  });
});
