import {test,expect,waitForOfflineReady} from './fixtures';
test('an installed update stays waiting while unsaved inputs and the old version remain usable',async({page,offlineServer})=>{
  await page.goto(offlineServer.url);await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await waitForOfflineReady(page);await expect(page.getByRole('complementary',{name:'Offline support'}).getByRole('status')).toContainText('ready for offline use');
  await page.getByLabel('Import .need').setInputFiles('artifacts/controls/widgets.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');await frame.getByLabel('Name',{exact:true}).fill('Keep this draft during update');
  await page.evaluate(()=>{(window as unknown as {previousWorker:ServiceWorker|null}).previousWorker=navigator.serviceWorker.controller;});offlineServer.update();await page.getByRole('button',{name:'Check for updates',exact:true}).click();await expect(page.getByText(/A new version is ready\. Save your inputs/)).toBeVisible();
  expect(await page.evaluate(()=>navigator.serviceWorker.controller===(window as unknown as {previousWorker:ServiceWorker|null}).previousWorker)).toBe(true);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Keep this draft during update');await expect(page.getByRole('region',{name:'Unsaved input recovery'}).getByRole('status')).toContainText('1 unsaved input');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('region',{name:'Unsaved input recovery'}).getByRole('status')).toContainText('0 unsaved inputs');
});
test('install icons and visible offline navigation remain cached after the server stops',async({page,offlineServer,context},info)=>{
  await page.goto(offlineServer.url);await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await waitForOfflineReady(page);const manifest=await page.evaluate(async()=>await(await fetch('/manifest.webmanifest')).json());expect(manifest.icons).toEqual(expect.arrayContaining([expect.objectContaining({sizes:'192x192'}),expect.objectContaining({sizes:'512x512',purpose:'maskable'})]));
  await offlineServer.stop();if(info.project.name==='webkit'){// WebKit's protocol offline switch can fail a controlled navigation internally.
    // The origin really is stopped; only its connectivity indicator is simulated.
    await page.addInitScript(()=>Object.defineProperty(navigator,'onLine',{get:()=>false}));
  }else await context.setOffline(true);await page.reload();await expect(page.getByRole('complementary',{name:'Offline support'}).getByRole('status')).toContainText('You are offline');for(const icon of manifest.icons)expect(await page.evaluate(async url=>(await fetch(url)).ok,icon.src)).toBe(true);
  await page.getByRole('link',{name:'Open saved encrypted applications',exact:true}).click();await expect(page.getByRole('heading',{name:'Encrypted applications',exact:true})).toBeVisible();await page.getByRole('link',{name:'Open saved local applications',exact:true}).click();await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();
});
