import {test,expect} from './fixtures';
import type {Page} from '@playwright/test';
async function open(page:Page){await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/widgets.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();await expect(page.frameLocator('iframe').getByLabel('Name',{exact:true})).toBeVisible();}
async function exported(page:Page){const pending=page.waitForEvent('download');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Export plaintext unsaved inputs',exact:true}).click();const stream=await(await pending).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();return JSON.parse(text);}
async function saved(page:Page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export plaintext data',exact:true}).click();const stream=await(await pending).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();return JSON.parse(text).values;}
const status=(page:Page)=>page.getByRole('region',{name:'Unsaved input recovery'}).getByRole('status');
async function dialogAction(page:Page,accept:boolean,action:()=>Promise<unknown>){const ready=page.waitForEvent('dialog');const running=action();const dialog=await ready;if(accept)await dialog.accept();else await dialog.dismiss();await running;}
const file=(value:unknown)=>({name:'drafts.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
test('unsaved inputs block replacement and navigation, recover explicitly, and never enter saved state',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe');await frame.getByLabel('Name',{exact:true}).fill('Private unsaved recovery');await expect(status(page)).toContainText('1 unsaved input');expect((await saved(page)).name.value).toBe('Original');
  await dialogAction(page,false,()=>page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click());await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private unsaved recovery');await dialogAction(page,false,()=>page.getByRole('link',{name:'Application registry',exact:true}).click());await expect(page).toHaveURL(/\/$/);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private unsaved recovery');
  expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})).toBe(true);
  const recovery=await exported(page);expect(recovery.format).toBe('needware-drafts-v1');expect(recovery.drafts[0].raw).toBe('Private unsaved recovery');
  await dialogAction(page,true,()=>page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click());await expect(status(page)).toContainText('0 unsaved inputs');await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Original');await expect(status(page)).toContainText('0 unsaved inputs');
  await page.getByLabel('Recover unsaved inputs').setInputFiles(file({...recovery,digest:'0'.repeat(64)}));await expect(page.getByRole('alert').filter({hasText:'different application, document, or signed revision'})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');
  page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(recovery));await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private unsaved recovery');const review=frame.getByRole('region',{name:'Review changed Name',exact:true});await expect(review).toBeVisible();await frame.getByRole('button',{name:'Save profile',exact:true}).click();expect((await saved(page)).name.value).toBe('Original');await review.getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');expect((await saved(page)).name.value).toBe('Private unsaved recovery');
});
test('invalid recovery is atomic and invalid raw input is preserved for correction',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe');await frame.getByLabel('Amount',{exact:true}).fill('1.234');const recovery=await exported(page);await dialogAction(page,true,()=>page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click());await expect(status(page)).toContainText('0 unsaved inputs');
  const bad={...recovery,drafts:[...recovery.drafts,{...recovery.drafts[0],id:'unavailable-field'}]};page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(bad));await expect(page.getByRole('alert').filter({hasText:'Recovery field is unavailable'})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');
  page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(recovery));await expect(frame.getByLabel('Amount',{exact:true})).toHaveValue('1.234');await expect(frame.getByRole('alert').filter({hasText:'Use at most 2 decimal places'})).toBeVisible();await frame.getByRole('region',{name:'Review changed Amount',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();expect((await saved(page)).amount.value.coefficient).toBe('900719925474099301');await frame.getByLabel('Amount',{exact:true}).fill('1.23');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');expect((await saved(page)).amount.value.coefficient).toBe('123');
});
test('an older durable acknowledgment never clears text edited while saving',async({page})=>{
  await page.addInitScript(()=>{const send=Worker.prototype.postMessage;let delayed=false;Worker.prototype.postMessage=function(...args:Parameters<Worker['postMessage']>){if(!delayed&&args[0]?.command?.kind==='dispatch'){delayed=true;setTimeout(()=>send.apply(this,args),500);return;}send.apply(this,args);};});
  await open(page);const frame=page.frameLocator('iframe'),name=frame.getByLabel('Name',{exact:true});await name.fill('First submitted');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await name.fill('Newer unsaved edit');await expect(status(page)).toContainText('pending changes');await expect.poll(async()=>(await saved(page)).name.value).toBe('First submitted');await expect(name).toHaveValue('Newer unsaved edit');await expect(status(page)).toContainText('1 unsaved input');await frame.getByRole('region',{name:'Review changed Name',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');expect((await saved(page)).name.value).toBe('Newer unsaved edit');
});
test('a rejected durable write keeps the submitted input dirty and recoverable',async({page,context})=>{
  await open(page);const frame=page.frameLocator('iframe');const other=await context.newPage();await other.goto('/');await other.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click();const second=other.frameLocator('iframe');await second.getByLabel('Name',{exact:true}).fill('Other tab committed');await second.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(other)).toContainText('0 unsaved inputs');
  await frame.getByLabel('Name',{exact:true}).fill('My rejected save');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:/Concurrent state change or quota exceeded|Application changed in another writer/i})).toBeVisible();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('My rejected save');await expect(status(page)).toContainText('1 unsaved input');expect((await exported(page)).drafts[0].raw).toBe('My rejected save');expect((await saved(other)).name.value).toBe('Other tab committed');await other.close();
});
