import {test,expect} from './fixtures';
import {readFileSync} from 'node:fs';
test('opaque WASM savepoints bind an instance and restore controls with data',async({page})=>{
  await page.goto('/');const bytes=[...readFileSync('artifacts/controls/runtime.need')];const result=await page.evaluate(async bytes=>{
    const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const runtime=new wasm.BrowserRuntime(new Uint8Array(bytes),undefined,true),other=new wasm.BrowserRuntime(new Uint8Array(bytes),undefined,true),dispatch=(name:string)=>runtime.dispatch(JSON.stringify({action:name,values:{},now:'2026-10-05T00:00:00Z',timezone:'UTC'}));
    dispatch('show_dialog');const before=runtime.view(),state=runtime.snapshot(),cut=runtime.savepoint();let invalid=false,foreign=false;try{dispatch('failed_navigation');}catch{invalid=true;}if(runtime.view()!==before||runtime.snapshot()!==state)throw Error('Failed sequence changed its cut');dispatch('details');runtime.restore_savepoint(cut);const restored=runtime.view()===before;try{other.restore_savepoint(cut);}catch{foreign=true;}cut.free();runtime.free();other.free();return {invalid,foreign,restored};
  },bytes);expect(result).toEqual({invalid:true,foreign:true,restored:true});
});
test('sandboxed native navigation, modal focus/escape and drawer close work in the consumer',async({page})=>{
  page.on('pageerror',error=>{throw error;});
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/runtime.need');await expect(page.getByRole('heading',{name:'Review Runtime controls fixture',exact:true})).toBeVisible();await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');
  await expect(frame.getByRole('heading',{name:'Controls home',exact:true})).toBeVisible();await frame.getByRole('button',{name:'Show dialog',exact:true}).click();const dialog=frame.getByRole('dialog',{name:'Review dialog',exact:true});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Close Review dialog',exact:true})).toBeFocused();await dialog.getByRole('button',{name:'Close Review dialog',exact:true}).press('Tab');await expect(dialog.getByRole('button',{name:'Close Review dialog',exact:true})).toBeFocused();await dialog.getByRole('button',{name:'Close Review dialog',exact:true}).press('Escape');await expect(dialog).not.toBeVisible();await expect(frame.getByRole('button',{name:'Show dialog',exact:true})).toBeFocused();
  await frame.getByRole('button',{name:'Show drawer',exact:true}).click();await expect(frame.getByRole('dialog',{name:'Preferences drawer',exact:true})).toBeVisible();await frame.getByRole('button',{name:'Close Preferences drawer',exact:true}).click();await expect(frame.getByRole('dialog',{name:'Preferences drawer',exact:true})).not.toBeVisible();
  await frame.getByRole('button',{name:'Open details',exact:true}).click();await expect(frame.getByRole('heading',{name:'Controls details',exact:true})).toBeVisible();await frame.getByRole('button',{name:'Open review',exact:true}).click();await expect(frame.getByRole('heading',{name:'Controls review',exact:true})).toBeVisible();await frame.getByRole('button',{name:'Back to previous screen',exact:true}).click();await expect(frame.getByRole('heading',{name:'Controls details',exact:true})).toBeVisible();await frame.getByRole('button',{name:'Back to previous screen',exact:true}).click();await expect(frame.getByRole('heading',{name:'Controls home',exact:true})).toBeVisible();
  await frame.getByRole('button',{name:'Fail atomic navigation',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'record id must be UUID'})).toBeVisible();await expect(frame.getByRole('heading',{name:'Controls home',exact:true})).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export plaintext data',exact:true}).click();const stream=await(await download).createReadStream();let raw='';for await(const chunk of stream!)raw+=chunk.toString();expect(JSON.parse(raw).values.counter).toEqual({type:'integer',value:'0'});
  await page.reload();await page.getByRole('button',{name:'Open Runtime controls fixture',exact:true}).click();await expect(frame.getByRole('heading',{name:'Controls home',exact:true})).toBeVisible();await expect(frame.getByRole('dialog')).toHaveCount(0);
});
