import {test,expect} from './fixtures';
test('verified raster, exact chart, calendar, record table and keyboard tabs work in the isolated consumer',async({page})=>{
  const external:string[]=[];page.on('request',request=>{if(!new URL(request.url()).hostname.match(/^(127\.0\.0\.1|localhost)$/)&&request.url().startsWith('http'))external.push(request.url());});
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/visuals.need');await expect(page.getByRole('heading',{name:'Review Visual components fixture',exact:true})).toBeVisible();await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');await expect(frame.getByRole('heading',{name:'Visual components',exact:true})).toBeVisible();const profile=frame.getByRole('tab',{name:'Profile',exact:true}),overview=frame.getByRole('tab',{name:'Overview',exact:true});await profile.focus();await profile.press('ArrowRight');await expect(overview).toBeFocused();await expect(overview).toHaveAttribute('aria-selected','true');
  const image=frame.getByRole('img',{name:'Verified checker sample',exact:true});await expect(image).toBeVisible();await expect.poll(()=>image.evaluate((image:HTMLImageElement)=>({complete:image.complete,width:image.naturalWidth,scheme:image.src.split(':')[0]}))).toEqual({complete:true,width:16,scheme:'blob'});await expect(frame.getByRole('img',{name:'Verified sample',exact:true})).toBeVisible();const chart=frame.getByRole('table',{name:'Signed totals exact values',exact:true});await expect(chart.getByRole('row',{name:'Exact large 9007199254740993',exact:true})).toBeVisible();await expect(chart.getByRole('row',{name:'Negative -20',exact:true})).toBeVisible();const calendar=frame.getByRole('table',{name:'October plans · October 2026',exact:true});await expect(calendar.getByText('Review budget',{exact:true})).toBeVisible();await expect(calendar.getByRole('columnheader')).toHaveCount(7);
  await frame.getByLabel('Record name',{exact:true}).fill('First record');await frame.getByRole('button',{name:'Add record',exact:true}).click();const table=frame.getByRole('table',{name:'Records',exact:true});await expect(table.getByRole('row',{name:'First record Complete',exact:true})).toBeVisible();await table.getByRole('button',{name:'Complete',exact:true}).click();await expect(table.getByRole('button',{name:'Undo',exact:true})).toBeVisible();await frame.getByLabel('Record name',{exact:true}).fill('Second record');await frame.getByRole('button',{name:'Add record',exact:true}).click();await expect(table.getByRole('row')).toHaveCount(3);await expect(table.getByRole('row',{name:'Second record Complete',exact:true})).toBeVisible();
  await overview.focus();await overview.press('Home');await expect(profile).toBeFocused();await expect(frame.getByLabel('Name',{exact:true})).toBeVisible();await frame.getByLabel('Name',{exact:true}).fill('Draft across tabs');await profile.press('End');await overview.press('Home');await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Draft across tabs');await page.setViewportSize({width:360,height:780});await profile.press('End');await expect(image).toBeVisible();expect(await frame.locator('body').evaluate(body=>body.scrollWidth<=body.clientWidth+1)).toBe(true);expect(external).toEqual([]);
  await page.reload();await page.getByRole('button',{name:'Open Visual components fixture',exact:true}).click();await frame.getByRole('tab',{name:'Overview',exact:true}).click();await expect(table.getByRole('row')).toHaveCount(3);await expect(image).toBeVisible();
});
