import {test,expect} from './fixtures';
import type {Page} from '@playwright/test';
async function open(page:Page){await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/widgets.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();await expect(page.frameLocator('iframe').getByLabel('Name',{exact:true})).toBeVisible();}
async function exported(page:Page){const pending=page.waitForEvent('download');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Export plaintext unsaved inputs',exact:true}).click();const stream=await(await pending).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();return JSON.parse(text);}
async function saved(page:Page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export plaintext data',exact:true}).click();const stream=await(await pending).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();return JSON.parse(text).values;}
const status=(page:Page)=>page.getByRole('region',{name:'Unsaved input recovery'}).getByRole('status');
async function dialogAction(page:Page,accept:boolean,action:()=>Promise<unknown>){const ready=page.waitForEvent('dialog');const running=action();const dialog=await ready;if(accept)await dialog.accept();else await dialog.dismiss();await running;}
const file=(value:unknown)=>({name:'drafts.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
test('real browser back and forward keep unsaved inputs until the user approves leaving',async({page})=>{
  await page.goto('/registry');const originTime=await page.evaluate(()=>performance.timeOrigin);await page.getByRole('link',{name:'needware /',exact:true}).click();await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();expect(await page.evaluate(()=>performance.timeOrigin)).not.toBe(originTime);
  await page.getByLabel('Import .need').setInputFiles('artifacts/controls/widgets.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');await frame.getByLabel('Name',{exact:true}).fill('Protected back navigation');
  await expect(status(page)).toContainText('1 unsaved input');const pendingQuestion=page.waitForEvent('dialog');await page.evaluate(()=>history.back());const question=await pendingQuestion;expect(question.type()).toBe('beforeunload');await question.dismiss();await expect(page).toHaveURL(/\/$/);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Protected back navigation');await expect(status(page)).toContainText('1 unsaved input');
  const accepted=page.goBack(),approval=await page.waitForEvent('dialog');expect(approval.type()).toBe('beforeunload');await approval.accept();await accepted;await expect(page.getByRole('heading',{name:'Application registry',exact:true})).toBeVisible();
  await page.goForward();await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click();await frame.getByLabel('Name',{exact:true}).fill('Protected forward navigation');
  await dialogAction(page,true,()=>page.getByRole('link',{name:'Application registry',exact:true}).click());await expect(page.getByRole('heading',{name:'Application registry',exact:true})).toBeVisible();await page.goBack();await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click();await frame.getByLabel('Name',{exact:true}).fill('Forward stays unsaved');
  await expect(status(page)).toContainText('1 unsaved input');const pendingForwardQuestion=page.waitForEvent('dialog');await page.evaluate(()=>history.forward());const forwardQuestion=await pendingForwardQuestion;expect(forwardQuestion.type()).toBe('beforeunload');await forwardQuestion.dismiss();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Forward stays unsaved');await expect(status(page)).toContainText('1 unsaved input');
});
test('ambiguous legacy fields preserve both drafts and block an uncertain submission',async({page})=>{
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/ambiguous-drafts.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');await frame.getByLabel('Home draft',{exact:true}).fill('First private input');await frame.getByLabel('Second home draft',{exact:true}).fill('Second private input');await expect(status(page)).toContainText('2 unsaved inputs');
  await frame.getByRole('button',{name:'Save Home draft',exact:true}).click();await expect(frame.getByRole('alert').filter({hasText:'Multiple inputs use the same field'})).toBeVisible();await expect(frame.getByLabel('Home draft',{exact:true})).toHaveValue('First private input');await expect(frame.getByLabel('Second home draft',{exact:true})).toHaveValue('Second private input');expect((await exported(page)).drafts.map((draft:{raw:unknown})=>draft.raw).sort()).toEqual(['First private input','Second private input']);
});
test('native navigation never acknowledges unrelated edits and same-field screens retain independent drafts',async({page})=>{
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/draft-screens.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');
  await frame.getByLabel('Home draft',{exact:true}).fill('Home text not submitted');await frame.getByRole('button',{name:'Open details',exact:true}).click();await expect(frame.getByLabel('Details draft',{exact:true})).toBeVisible();await expect(status(page)).toContainText('1 unsaved input');
  await frame.getByLabel('Details draft',{exact:true}).fill('Independent details text');await expect(status(page)).toContainText('2 unsaved inputs');await frame.getByRole('button',{name:'Return home',exact:true}).click();await expect(frame.getByLabel('Home draft',{exact:true})).toHaveValue('Home text not submitted');expect((await exported(page)).drafts.map((draft:{raw:unknown})=>draft.raw).sort()).toEqual(['Home text not submitted','Independent details text'].sort());
  await frame.getByRole('button',{name:'Save Home draft',exact:true}).click();await expect(status(page)).toContainText('1 unsaved input');await frame.getByRole('button',{name:'Open details',exact:true}).click();await expect(frame.getByLabel('Details draft',{exact:true})).toHaveValue('Independent details text');await frame.getByRole('button',{name:'Save Details draft',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');
});
test('multi-screen recovery imports only an explicitly reviewed screen and accepts exact legacy field identities',async({page})=>{
  await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/draft-screens.need');await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();const frame=page.frameLocator('iframe');
  await frame.getByLabel('Home draft',{exact:true}).fill('Recovered home');await frame.getByRole('button',{name:'Open details',exact:true}).click();await frame.getByLabel('Details draft',{exact:true}).fill('Recovered details');const recovery=await exported(page);expect(new Set(recovery.drafts.map((draft:{scope:string})=>draft.scope)).size).toBe(2);const legacy={...recovery,drafts:recovery.drafts.map((draft:object)=>({...draft,scope:'global'}))};
  await dialogAction(page,true,()=>page.getByRole('button',{name:'Open Cross-screen drafts fixture',exact:true}).click());await expect(frame.getByLabel('Home draft',{exact:true})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');await expect(page.getByLabel('Recover unsaved inputs')).toBeEnabled();page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file({...recovery,drafts:[recovery.drafts[0],{...recovery.drafts[0],scope:'global'}]}));await expect(page.getByRole('alert').filter({hasText:'Duplicate recovered field'})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');
  page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(legacy));await expect(page.getByRole('alert').filter({hasText:'Recovery field is unavailable'})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');await expect(page.getByText('2 inputs remain to recover.',{exact:false})).toBeVisible();
  await dialogAction(page,true,()=>page.getByRole('button',{name:'Recover inputs on this screen',exact:true}).click());await expect(frame.getByLabel('Home draft',{exact:true})).toHaveValue('Recovered home');await expect(page.getByText('1 inputs remain to recover.',{exact:false})).toBeVisible();await frame.getByRole('region',{name:'Review changed Home draft',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save Home draft',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');
  await frame.getByRole('button',{name:'Open details',exact:true}).click();await dialogAction(page,true,()=>page.getByRole('button',{name:'Recover inputs on this screen',exact:true}).click());await expect(frame.getByLabel('Details draft',{exact:true})).toHaveValue('Recovered details');await frame.getByRole('region',{name:'Review changed Details draft',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save Details draft',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');await expect(page.getByRole('button',{name:'Recover inputs on this screen',exact:true})).toHaveCount(0);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export plaintext data',exact:true}).click();const stream=await(await download).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();const records=Object.values(JSON.parse(text).collections.habits) as {name:{value:string}}[];expect(records.map(row=>row.name.value).sort()).toEqual(['Recovered details','Recovered home']);
});
test('unsaved inputs block replacement and navigation, recover explicitly, and never enter saved state',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe');await frame.getByLabel('Name',{exact:true}).fill('Private unsaved recovery');await expect(status(page)).toContainText('1 unsaved input');expect((await saved(page)).name.value).toBe('Original');
  await dialogAction(page,false,()=>page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click());await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private unsaved recovery');await dialogAction(page,false,()=>page.getByRole('link',{name:'Application registry',exact:true}).click());await expect(page).toHaveURL(/\/$/);await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private unsaved recovery');
  expect(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;})).toBe(true);
  const recovery=await exported(page);expect(recovery.format).toBe('needware-drafts-v1');expect(recovery.drafts[0].raw).toBe('Private unsaved recovery');
  await dialogAction(page,true,()=>page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click());await expect(status(page)).toContainText('0 unsaved inputs');await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Original');await expect(status(page)).toContainText('0 unsaved inputs');
  await page.getByLabel('Recover unsaved inputs').setInputFiles(file({...recovery,digest:'0'.repeat(64)}));await expect(page.getByRole('alert').filter({hasText:'different application, document, or signed revision'})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');
  page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(recovery));await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Private unsaved recovery');const review=frame.getByRole('region',{name:'Review changed Name',exact:true});await expect(review).toBeVisible();await frame.getByRole('button',{name:'Save profile',exact:true}).click();expect((await saved(page)).name.value).toBe('Original');await review.getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');expect((await saved(page)).name.value).toBe('Private unsaved recovery');
});
test('invalid recovery is atomic and invalid raw input is preserved for correction',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe');await frame.getByLabel('Amount',{exact:true}).fill('1.234');const recovery=await exported(page);await dialogAction(page,true,()=>page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click());await expect(status(page)).toContainText('0 unsaved inputs');
  const bad={...recovery,drafts:[...recovery.drafts,{...recovery.drafts[0],id:'unavailable-field'}]};page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(bad));await expect(page.getByRole('alert').filter({hasText:'Recovery field is unavailable'})).toBeVisible();await expect(status(page)).toContainText('0 unsaved inputs');
  page.once('dialog',dialog=>dialog.accept());await page.getByLabel('Recover unsaved inputs').setInputFiles(file(recovery));await expect(frame.getByLabel('Amount',{exact:true})).toHaveValue('1.234');await expect(frame.getByRole('alert').filter({hasText:'Use at most 2 decimal places'})).toBeVisible();await frame.getByRole('region',{name:'Review changed Amount',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();expect((await saved(page)).amount.value.coefficient).toBe('900719925474099301');await frame.getByLabel('Amount',{exact:true}).fill('1.23');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');expect((await saved(page)).amount.value.coefficient).toBe('123');
});
test('an older durable acknowledgment never clears text edited while saving',async({page})=>{
  await page.addInitScript(()=>{const send=Worker.prototype.postMessage;let delayed=false;Worker.prototype.postMessage=function(...args:Parameters<Worker['postMessage']>){if(!delayed&&args[0]?.command?.kind==='dispatch'){delayed=true;setTimeout(()=>send.apply(this,args),500);return;}send.apply(this,args);};});
  await open(page);const frame=page.frameLocator('iframe'),name=frame.getByLabel('Name',{exact:true});await name.fill('First submitted');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await name.fill('Newer unsaved edit');await expect(status(page)).toContainText('pending changes');await expect.poll(async()=>(await saved(page)).name.value).toBe('First submitted');await expect(name).toHaveValue('Newer unsaved edit');await expect(status(page)).toContainText('1 unsaved input');await frame.getByRole('region',{name:'Review changed Name',exact:true}).getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(page)).toContainText('0 unsaved inputs');expect((await saved(page)).name.value).toBe('Newer unsaved edit');
});
test('a rejected durable write keeps the submitted input dirty and recoverable',async({page,context})=>{
  await open(page);const frame=page.frameLocator('iframe');const other=await context.newPage();await other.goto('/');await other.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click();const second=other.frameLocator('iframe');await second.getByLabel('Name',{exact:true}).fill('Other tab committed');await second.getByRole('button',{name:'Save profile',exact:true}).click();await expect(status(other)).toContainText('0 unsaved inputs');
  await frame.getByLabel('Name',{exact:true}).fill('My rejected save');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:/Concurrent state change or quota exceeded|Application changed in another writer/i})).toBeVisible();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('My rejected save');await expect(status(page)).toContainText('1 unsaved input');expect((await exported(page)).drafts[0].raw).toBe('My rejected save');expect((await saved(other)).name.value).toBe('Other tab committed');await other.close();
});
