import {test,expect} from './fixtures';
import type {Page} from '@playwright/test';
async function open(page:Page){await page.goto('/');await expect(page.getByText('Local runtime ready',{exact:true})).toBeVisible();await page.getByLabel('Import .need').setInputFiles('artifacts/controls/widgets.need');await expect(page.getByRole('heading',{name:'Review Typed widgets fixture',exact:true})).toBeVisible();await page.getByRole('button',{name:'Trust signer and run application',exact:true}).click();await expect(page.frameLocator('iframe').getByRole('heading',{name:'Typed widgets',exact:true})).toBeVisible();}
async function state(page:Page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export plaintext data',exact:true}).click();const stream=await(await pending).createReadStream();let text='';for await(const chunk of stream!)text+=chunk.toString();return JSON.parse(text).values;}
test('typed forms preserve exact decimals and isolate two profiles through cold reopen',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe'),primary=frame.getByRole('form',{name:'Save profile',exact:true});
  await expect(primary.getByLabel('Amount',{exact:true})).toHaveValue('9007199254740993.01');await primary.getByLabel('Name',{exact:true}).fill('Alice');await frame.getByLabel('Second name',{exact:true}).fill('Bob');await primary.getByLabel('Amount',{exact:true}).fill('9007199254740993.02');await primary.getByLabel('Accepted',{exact:true}).check();await primary.getByRole('switch',{name:'Notify',exact:true}).check();await primary.getByLabel('Mode',{exact:true}).selectOption('Bright');await primary.getByRole('radio',{name:'Bright',exact:true}).check();await primary.getByLabel('Labels',{exact:true}).selectOption(['Calm','Bright']);await primary.getByRole('slider',{name:'Level',exact:true}).press('End');await primary.getByLabel('Birthday',{exact:true}).fill('2026-10-06');await primary.getByLabel('At (UTC)',{exact:true}).fill('2026-10-06T13:14');await primary.getByRole('button',{name:'Save profile',exact:true}).click();
  await expect.poll(async()=> (await state(page)).name.value).toBe('Alice');let values=await state(page);expect(values.secondary_name.value).toBe('Second original');expect(values.amount).toEqual({type:'decimal',value:{coefficient:'900719925474099302',scale:2}});expect(values.accepted.value).toBe(true);expect(values.notify.value).toBe(true);expect(values.mode.value).toBe('Bright');expect(values.priority.value).toBe('Bright');expect(values.labels.value).toEqual([{type:'string',value:'Calm'},{type:'string',value:'Bright'}]);expect(values.level.value).toBe('100');expect(values.birthday.value).toBe('2026-10-06');expect(values.at.value).toBe('2026-10-06T13:14:00.000Z');
  await frame.getByRole('button',{name:'Save second profile',exact:true}).click();await expect.poll(async()=> (await state(page)).secondary_name.value).toBe('Bob');await page.reload();await page.getByRole('button',{name:'Open Typed widgets fixture',exact:true}).click();await expect(frame.getByLabel('Name',{exact:true})).toHaveValue('Alice');await expect(frame.getByLabel('Second name',{exact:true})).toHaveValue('Bob');await expect(frame.getByLabel('Amount',{exact:true})).toHaveValue('9007199254740993.02');
});
test('a changed saved value preserves the draft and requires an explicit review',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe'),input=frame.getByLabel('Name',{exact:true});await input.fill('My preserved draft');await frame.getByRole('button',{name:'Change saved name',exact:true}).click();const review=frame.getByRole('region',{name:'Review changed Name',exact:true});await expect(review).toBeVisible();await expect(input).toHaveValue('My preserved draft');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect(frame.getByRole('alert').filter({hasText:'Review changed values before submitting.'})).toBeVisible();expect((await state(page)).name.value).toBe('Server changed');await review.getByRole('button',{name:'Keep my draft',exact:true}).click();await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect.poll(async()=> (await state(page)).name.value).toBe('My preserved draft');await input.fill('Another draft');await frame.getByRole('button',{name:'Change saved name',exact:true}).click();await expect(review).toBeVisible();await review.getByRole('button',{name:'Use saved value',exact:true}).click();await expect(input).toHaveValue('Server changed');await expect(review).not.toBeVisible();
});
test('invalid decimal editing does not replay a previous valid value',async({page})=>{
  await open(page);const frame=page.frameLocator('iframe'),input=frame.getByLabel('Amount',{exact:true});await input.fill('1.234');await expect(frame.getByRole('alert').filter({hasText:'Use at most 2 decimal places.'})).toBeVisible();await frame.getByRole('button',{name:'Save profile',exact:true}).click();expect((await state(page)).amount.value.coefficient).toBe('900719925474099301');await input.fill('1.23');await frame.getByRole('button',{name:'Save profile',exact:true}).click();await expect.poll(async()=> (await state(page)).amount.value.coefficient).toBe('123');
});
