'use client';
import {useEffect,useState,useSyncExternalStore} from 'react';
import {registerOfflineShell} from '../lib/offline-shell';
import OfflineLink from './offline-link';
const subscribeOnline=(listener:()=>void)=>{window.addEventListener('online',listener);window.addEventListener('offline',listener);return()=>{window.removeEventListener('online',listener);window.removeEventListener('offline',listener);};};
export default function OfflineSupport(){
  const online=useSyncExternalStore(subscribeOnline,()=>navigator.onLine,()=>true);
  const [ready,setReady]=useState(false),[waiting,setWaiting]=useState(false),[checking,setChecking]=useState(false),[error,setError]=useState('');
  const [registration,setRegistration]=useState<ServiceWorkerRegistration>();
  useEffect(()=>{
    let active=true;async function prepare(){if(!('serviceWorker' in navigator))throw Error('This browser cannot install offline support. Keep it online and export important data.');await registerOfflineShell();const current=await navigator.serviceWorker.getRegistration();if(active){setRegistration(current);setReady(Boolean(navigator.serviceWorker.controller));setWaiting(Boolean(current?.waiting));}}
    void prepare().catch(failure=>{if(active)setError(String(failure));});return()=>{active=false;};
  },[]);
  useEffect(()=>{if(!registration)return;let installing=registration.installing;const changed=()=>{setReady(Boolean(navigator.serviceWorker.controller));setWaiting(Boolean(registration.waiting));};const update=()=>{installing?.removeEventListener('statechange',changed);installing=registration.installing;installing?.addEventListener('statechange',changed);changed();};installing?.addEventListener('statechange',changed);registration.addEventListener('updatefound',update);navigator.serviceWorker.addEventListener('controllerchange',changed);return()=>{installing?.removeEventListener('statechange',changed);registration.removeEventListener('updatefound',update);navigator.serviceWorker.removeEventListener('controllerchange',changed);};},[registration]);
  async function check(){setChecking(true);setError('');try{if(!navigator.onLine)throw Error('Reconnect before checking for updates. Your current version stays available.');await registerOfflineShell();const value=await navigator.serviceWorker.getRegistration();setRegistration(value);if(!value)throw Error('Offline support is not installed. Reload while online to retry.');await value.update();setReady(Boolean(navigator.serviceWorker.controller));setWaiting(Boolean(value.waiting));}catch(failure){setError(String(failure));}finally{setChecking(false);}}
  return <aside className="offline-support" aria-label="Offline support"><div><h2>Available on this browser</h2><p role="status" aria-live="polite">{ready?(online?'Saved local and encrypted applications are ready for offline use. Account and cloud features need a connection.':'You are offline. Saved applications remain available; account and cloud features need a connection.'):'Preparing offline access. Keep this page online until setup finishes.'}</p>{waiting&&<p className="notice">A new version is ready. Save your inputs or export a draft recovery file, close all Needware tabs, then reopen to use it. This page keeps its current version.</p>}{error&&<p role="alert" className="notice error">{error}</p>}</div><div className="toolbar"><OfflineLink href="/">Open saved local applications</OfflineLink><OfflineLink href="/encrypted">Open saved encrypted applications</OfflineLink><button disabled={checking||!online} onClick={()=>void check()}>{checking?'Checking for updates…':'Check for updates'}</button></div></aside>;
}
