'use client';
import Link from '../offline-link';
import {useEffect,useRef,useState} from 'react';
import canonicalize from 'canonicalize';
import type {RegistryEntry} from '../../lib/registry-store';
const base64=(bytes:Uint8Array)=>{const parts=[];for(let i=0;i<bytes.length;i+=8192)parts.push(String.fromCharCode(...bytes.subarray(i,i+8192)));return btoa(parts.join(''));};
export default function RegistryPanel(){
  const draftId=useRef('');
  const [entries,setEntries]=useState<RegistryEntry[]>([]),[account,setAccount]=useState(''),[documents,setDocuments]=useState<{id:string;ready:boolean}[]>([]);
  const [editing,setEditing]=useState<RegistryEntry|null>(null),[title,setTitle]=useState(''),[summary,setSummary]=useState(''),[visibility,setVisibility]=useState<RegistryEntry['visibility']>('private');
  const [document,setDocument]=useState(''),[packageBytes,setPackageBytes]=useState<Uint8Array|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('Loading applications'),[error,setError]=useState('');
  const [source,setSource]=useState<{entry:string;digest:string}|null>(null);
  async function refresh(){const response=await fetch('/api/registry',{cache:'no-store'}),value=await response.json();if(!response.ok)throw Error(value.message);setEntries(value.applications);}
  useEffect(()=>{let active=true;(async()=>{try{
    const response=await fetch('/api/registry',{cache:'no-store'}),value=await response.json();if(!response.ok)throw Error(value.message);if(active){setEntries(value.applications);setStatus('Applications ready');const query=new URLSearchParams(window.location.search),entry=query.get('source'),digest=query.get('revision');if(entry&&digest&&/^[0-9a-f-]{36}$/.test(entry)&&/^[0-9a-f]{64}$/.test(digest)){setSource({entry,digest});setVisibility('unlisted');}}
    const session=await(await fetch('/api/auth/get-session',{cache:'no-store'})).json();if(active&&session?.user?.emailVerified){setAccount(session.user.id);const list=await(await fetch('/api/documents',{cache:'no-store'})).json();if(active)setDocuments(list.documents??[]);}
  }catch(error){if(active)setError(String(error));}})();return()=>{active=false;};},[]);
  async function run(task:()=>Promise<void>){setBusy(true);setError('');try{await task();}catch(error){setError(String(error));}finally{setBusy(false);}}
  function edit(entry:RegistryEntry|null){draftId.current=entry?.id??crypto.randomUUID();setEditing(entry);setTitle(entry?.title??'');setSummary(entry?.summary??'');setVisibility(entry?.visibility??'private');setDocument(entry?.document_id??'');setPackageBytes(null);setConsent(false);setStatus(entry?'Editing publication':'New publication');}
  async function publish(){
    if(!consent)throw Error('Review publication visibility first');
    if(!draftId.current)draftId.current=crypto.randomUUID();
    const response=await fetch('/api/registry',{method:'POST',headers:{'Content-Type':'application/json'},body:canonicalize({action:'publish',id:editing?.id??draftId.current,expected_version:Number(editing?.version??0),visibility,title,summary,document:visibility==='private'?document:null,package:visibility==='private'?null:packageBytes?base64(packageBytes):null,source:editing?.source_entry?{entry:editing.source_entry,digest:editing.source_digest}:source})});
    const result=await response.json();if(!response.ok)throw Error(result.message);edit(result.application);await refresh();setStatus('Application published. Its sharing URL stays the same across revisions.');
  }
  return <><header><Link href="/">needware /</Link><nav><Link href="/encrypted">Your encrypted apps</Link><Link href="/account">Your account</Link></nav></header><main id="main"><span className="eyebrow">Software worth sharing</span><h1>Application registry</h1><p>Discover public applications, or publish a definition for others to review and use.</p><p role="status" aria-live="polite">{status}</p>{error&&<p role="alert" className="notice error">{error}</p>}
    {account?<section aria-label="Publish an application"><h2>{editing?'Update application':'Publish an application'}</h2><button disabled={busy} onClick={()=>{edit(null);setSource(null);}}>New application</button>{source&&<p>Publishing an independent remix of <Link href={`/a/${source.entry}?revision=${source.digest}`}>this signed source revision</Link>. Upload the remix definition downloaded after review.</p>}
      <form onSubmit={event=>{event.preventDefault();void run(publish);}}><label>Application title<input required maxLength={120} value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Application summary<textarea maxLength={1000} value={summary} onChange={event=>setSummary(event.target.value)}/></label>
        <label>Visibility<select aria-label="Visibility" value={visibility} onChange={event=>{setVisibility(event.target.value as RegistryEntry['visibility']);setConsent(false);}}><option value="private">Private — only your account</option><option value="unlisted">Unlisted — anyone with the link</option><option value="public">Public — discoverable in the registry</option></select></label>
        {visibility==='private'?<label>Encrypted cloud application<select required value={document} onChange={event=>setDocument(event.target.value)}><option value="">Choose a synced application</option>{documents.filter(item=>item.ready).map(item=><option key={item.id} value={item.id}>{item.id}</option>)}</select></label>:<label>Signed application definition<input required type="file" accept=".need" onChange={event=>{const file=event.target.files?.[0];setPackageBytes(null);setConsent(false);if(file)void run(async()=>{if(file.size>4194304)throw Error('Published packages are limited to 4 MiB');setPackageBytes(new Uint8Array(await file.arrayBuffer()));});}}/></label>}
        <p className="notice">{visibility==='private'?'The definition stays encrypted. Opening it requires your vault and current document access.':'Publishing makes this definition and its included assets downloadable. Review the package for private content first. Changing visibility cannot erase copies already downloaded.'}</p>
        <label><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/> I reviewed the definition and selected visibility</label><button disabled={busy||!consent||visibility!=='private'&&!packageBytes} className="primary" type="submit">Publish application</button>
      </form></section>:<p><Link href="/account">Sign in with a verified account</Link> to publish.</p>}
    <section aria-label="Applications"><h2>Applications</h2>{entries.length===0&&<p>No applications have been published yet.</p>}{entries.map(entry=><article key={entry.id} className="app-card"><h3><Link href={`/a/${entry.id}`}>{entry.title}</Link></h3><p>{entry.summary}</p><p>{entry.visibility} · revision {entry.current_digest.slice(0,12)}</p>{entry.owner_id===account&&<><button disabled={busy} onClick={()=>edit(entry)}>Edit {entry.title}</button><button disabled={busy} onClick={()=>{if(window.confirm('Delete this registry entry and its hosted definitions? Downloaded copies remain available.'))void run(async()=>{const response=await fetch('/api/registry',{method:'POST',headers:{'Content-Type':'application/json'},body:canonicalize({action:'delete',id:entry.id,expected_version:Number(entry.version)})});const result=await response.json();if(!response.ok)throw Error(result.message);edit(null);await refresh();setStatus('Registry entry deleted');});}}>Delete {entry.title}</button></>}</article>)}</section>
  </main></>;
}
