'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from '../offline-link';
import canonicalize from 'canonicalize';
import Script from 'next/script';
import {authClient} from '../../lib/auth-client';
type Price={id:string;amount:number;currency:string;interval:'month';livemode:boolean};
type Billing={provider:'stripe'|'cashfree'|'disabled';configured:boolean;checkout_available:boolean;price:Price|null;checkout:{id:string;expires_at:string}|null;account:{status:string;paid_until:string|null;has_customer:boolean}|null;usage:{plan:string;creation_hold:boolean;quota:{daily:number;monthly:number;budget:number};resets_at:string}};
declare global{interface Window{Cashfree?:(options:{mode:'sandbox'|'production'})=>{subscriptionsCheckout:(options:{subsSessionId:string;redirectTarget:'_self'})=>Promise<{error?:{message?:string}}>};}}
const message=(failure:unknown)=>failure instanceof Error?failure.message:'Billing is temporarily unavailable. Please try again.';
export default function BillingPanel(){const {data:session,isPending}=authClient.useSession();return <BillingDetails key={session?.user.id??'signedout'} account={session?.user.id} pending={isPending}/>;}
function BillingDetails({account,pending}:{account?:string;pending:boolean}){
  const [data,setData]=useState<Billing|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[consentedReview,setConsentedReview]=useState<string|null>(null),[phone,setPhone]=useState(''),[cancelConsent,setCancelConsent]=useState(false),[sdk,setSdk]=useState(false);const request=useRef<{price:string;id:string}|null>(null);
  const refresh=useCallback(async(signal?:AbortSignal)=>{if(!account)return;const response=await fetch('/api/billing',{cache:'no-store',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(15000)]):AbortSignal.timeout(15000)}),value=await response.json();if(!response.ok)throw Error(value.message??'Billing unavailable');signal?.throwIfAborted();setData(value);setError('');},[account]);
  useEffect(()=>{const controller=new AbortController();let loading=false;const load=async()=>{if(loading)return;loading=true;try{await refresh(controller.signal);}catch(failure){if(!controller.signal.aborted)setError(message(failure));}finally{loading=false;}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
  const price=data?.price,formatted=price?new Intl.NumberFormat(undefined,{style:'currency',currency:price.currency}).format(price.amount/100):'';
  const priceReview=price?(canonicalize(price)??null):null,consent=consentedReview!==null&&consentedReview===priceReview;
  async function open(action:'checkout'|'portal'|'cancel'){
    setBusy(true);setError('');try{
      let payload:unknown=action==='cancel'?{action,consent:cancelConsent}:{action};if(action==='cancel'&&!cancelConsent)throw Error('Review cancellation before continuing');if(action==='checkout'){if(!consent||!price||!data?.checkout_available)throw Error('New subscriptions are currently paused');const key=canonicalize({price,phone:data?.provider==='cashfree'?phone:''})!;if(data?.checkout)request.current={price:key,id:data.checkout.id};else if(request.current?.price!==key)request.current={price:key,id:crypto.randomUUID()};payload={action,id:request.current!.id,price,consent:true,...(data?.provider==='cashfree'?{phone}:{})};}
      const response=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:canonicalize(payload),signal:AbortSignal.timeout(30000)}),result=await response.json();if(!response.ok){if(response.status===409){request.current=null;setConsentedReview(null);await refresh();}throw Error(result.message??'Billing session unavailable');}
      if(action==='cancel'){if(result.cancelled!==true)throw Error('Cancellation was not confirmed');setCancelConsent(false);request.current=null;await refresh();return;}
      if(data?.provider==='cashfree'){if(result.provider!=='cashfree'||result.livemode!==price?.livemode||typeof result.session!=='string'||! /^[A-Za-z0-9_.-]{16,4096}$/.test(result.session)||!window.Cashfree)throw Error('Checkout identity rejected');const checkout=await window.Cashfree({mode:result.livemode?'production':'sandbox'}).subscriptionsCheckout({subsSessionId:result.session,redirectTarget:'_self'});if(checkout.error)throw Error(checkout.error.message??'Cashfree checkout unavailable');return;}
      const url=new URL(result.url);if(url.protocol!=='https:'||url.hostname!==(action==='portal'?'billing.stripe.com':'checkout.stripe.com'))throw Error('Billing redirect rejected');window.location.assign(url.toString());
    }catch(failure){setError(message(failure));}finally{setBusy(false);}
  }
  return <><header><strong>needware /</strong><nav aria-label="Needware"><Link href="/generation">Your creations</Link><Link href="/account">Your account</Link><Link href="/">Create application</Link></nav></header><main id="main" className="billing-page" aria-busy={pending||busy}><h1>Billing and your plan</h1>
    {!account&&<p>{pending?'Checking your session…':<>Sign in with a verified account to review billing. <Link href="/account">Sign in or create an account</Link></>}</p>}{account&&!data&&!error&&<p role="status">Loading your plan…</p>}{error&&<p role="alert" className="notice error">{error}</p>}
    {data?.provider==='cashfree'&&data.checkout_available&&<Script src="https://sdk.cashfree.com/js/v3/cashfree.js" onReady={()=>setSdk(true)} onError={()=>setError('Cashfree checkout could not load. Try again later.')}/>}
    {data?.usage.creation_hold&&<p role="alert">Creation and new subscriptions are paused after operator review. Cancellation remains available.</p>}
    {data&&<><section aria-label="Current plan"><h2>{data.usage.plan==='pro'?'Pro':'Free'}</h2><p>{data.usage.quota.daily} creation requests each UTC day · {data.usage.quota.monthly} each calendar month. Creation is subject to service capacity and these limits.</p><p>Existing local and imported encrypted applications remain yours when a subscription ends. Paid access requires confirmed current payment state; stale verification returns creation to Free limits.</p>{data.account&&<p>Payment status: {data.account.status.replaceAll('_',' ')}{data.account.paid_until?` · confirmed through ${new Date(data.account.paid_until).toLocaleString()}`:''}. Checkout return alone does not activate paid access.</p>}</section>
      {price?<section aria-label="Pro subscription"><h2>Pro · {formatted} per month</h2>{!data.checkout_available&&<p className="notice" role="status">New subscriptions are paused while payment and creation services finish activation. You can still manage an existing subscription.</p>}{!price.livemode&&<p className="notice">{data.provider==='cashfree'?'Cashfree':'Stripe'} test billing. This installation cannot accept a real payment in this mode.</p>}<p>Renewal is automatic until cancellation. Payment details go directly to {data.provider==='cashfree'?'Cashfree':'Stripe'}. Creation remains subject to your plan limits and service capacity.</p>{data.provider==='cashfree'&&<><p>Cashfree authorizes ₹1 and refunds it. The first ₹499 charge is scheduled 48 hours after checkout creation. Pro starts only after a confirmed subscription charge.</p><label>10-digit Indian mobile number<input type="tel" pattern="[0-9]{10}" autoComplete="tel-national" inputMode="numeric" maxLength={10} value={phone} onChange={event=>{setPhone(event.target.value);setConsentedReview(null);}}/></label></>}<label><input type="checkbox" checked={consent} onChange={event=>setConsentedReview(event.target.checked?priceReview:null)}/> I reviewed {formatted} every month and automatic renewal until cancellation</label><button disabled={busy||!data.checkout_available||!consent||data.usage.plan==='pro'||data.usage.creation_hold||data.provider==='cashfree'&&(!sdk||!/^\d{10}$/.test(phone))} onClick={()=>{void open('checkout');}}>Continue to {data.provider==='cashfree'?'Cashfree':'Stripe'} checkout</button></section>:<p>Paid subscriptions are not available yet. Your saved and offline applications remain available.</p>}
      {data.configured&&data.account?.has_customer&&(data.provider==='cashfree'?<section aria-label="Cancellation"><label><input type="checkbox" checked={cancelConsent} onChange={event=>setCancelConsent(event.target.checked)}/> Stop future renewal. Confirmed paid access lasts until its verified end date.</label><button disabled={busy||!cancelConsent} onClick={()=>{void open('cancel');}}>Cancel subscription</button></section>:<button disabled={busy} onClick={()=>{void open('portal');}}>Manage subscription in Stripe</button>)}<button disabled={busy} onClick={()=>{void refresh().catch(failure=>setError(message(failure)));}}>Refresh verified payment state</button>
    </>}
  </main></>;
}
