import React,{useEffect,useRef,useState,type ReactNode,type KeyboardEvent} from 'react';
import type {ViewNode} from '@needware/ir-types/ViewNode';
import type {Value} from '@needware/ir-types/Value';
export function RuntimeImage({node}:{node:ViewNode}){
  const ref=useRef<HTMLImageElement>(null),[failed,setFailed]=useState(''),raster=node.raster,digest=raster?.digest,bytes=raster?.bytes_hex,media=raster?.media_type;
  useEffect(()=>{const element=ref.current;if(!element||!bytes||!digest||!media||!['image/png','image/jpeg','image/webp'].includes(media)||bytes.length>16*1024*1024||bytes.length%2||!/^[0-9a-f]+$/.test(bytes))return;
    const data=new Uint8Array(bytes.length/2);for(let i=0;i<data.length;i++)data[i]=Number.parseInt(bytes.slice(i*2,i*2+2),16);
    const url=URL.createObjectURL(new Blob([data],{type:media}));element.src=url;return()=>{element.removeAttribute('src');URL.revokeObjectURL(url);};
  },[digest,bytes,media]);
  return <figure className="runtime-image"><img ref={ref} width={raster?.width} height={raster?.height} alt={node.options.includes('decorative')?'':node.text} onError={()=>setFailed(digest??'invalid')}/>{node.text&&<figcaption>{node.text}</figcaption>}{failed&&failed===digest&&<p role="alert">This verified image could not be displayed.</p>}</figure>;
}
const icons:Record<string,string>={check:'✓',heart:'♥',clock:'◷',calendar:'▦',star:'★',info:'ⓘ',warning:'⚠',plus:'+',search:'⌕'};
function scrollRegion(event:KeyboardEvent<HTMLDivElement>){const element=event.currentTarget;if(event.target!==element||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||!['ArrowLeft','ArrowRight'].includes(event.key)||element.scrollWidth<=element.clientWidth)return;event.preventDefault();element.scrollLeft+=event.key==='ArrowRight'?80:-80;}
export function RuntimeIcon({node}:{node:ViewNode}){return <span role="img" aria-label={node.text} className="runtime-icon">{icons[node.options[0]]??'?'}</span>;}
export function RuntimeTable({node,render}:{node:ViewNode;render:(node:ViewNode)=>ReactNode}){
  const rows=new Map<string,ViewNode[]>();for(const child of node.children){const key=child.record??child.id,items=rows.get(key)??[];items.push(child);rows.set(key,items);}
  return <div className="runtime-table" role="region" aria-label={`${node.text||'Application'} table`} tabIndex={0} onKeyDown={scrollRegion}><table><caption>{node.text||'Application records'}</caption><thead><tr>{node.options.map((label,index)=><th scope="col" key={index}>{label}</th>)}</tr></thead><tbody>{[...rows].map(([key,items])=><tr key={key}>{items.map(child=><td key={child.id}>{render(child)}</td>)}</tr>)}</tbody></table>{!rows.size&&<p>Nothing here yet.</p>}</div>;
}
export function RuntimeTabs({node,render}:{node:ViewNode;render:(node:ViewNode)=>ReactNode}){
  const [selected,setSelected]=useState(node.children[0]?.id),buttons=useRef(new Map<string,HTMLButtonElement>()),active=node.children.find(child=>child.id===selected)??node.children[0];
  function choose(index:number){const child=node.children[(index+node.children.length)%node.children.length];if(child){setSelected(child.id);buttons.current.get(child.id)?.focus();}}
  return <section className="runtime-tabs"><div role="tablist" aria-label={node.text||'Application tabs'}>{node.children.map((child,index)=><button key={child.id} ref={element=>{if(element)buttons.current.set(child.id,element);else buttons.current.delete(child.id);}} type="button" role="tab" id={`${node.id}-tab-${child.id}`} aria-controls={`${node.id}-panel-${child.id}`} aria-selected={active?.id===child.id} tabIndex={active?.id===child.id?0:-1} disabled={node.disabled} onClick={()=>choose(index)} onKeyDown={event=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();choose(event.key==='Home'?0:event.key==='End'?node.children.length-1:index+(event.key==='ArrowRight'?1:-1));}}}>{node.options[index]}</button>)}</div>{node.children.map(child=><div key={child.id} role="tabpanel" hidden={active?.id!==child.id} tabIndex={0} id={`${node.id}-panel-${child.id}`} aria-labelledby={`${node.id}-tab-${child.id}`}>{render(child)}</div>)}</section>;
}
function records(value:Value|null|undefined):Record<string,Value>[] {return value?.type==='list'?value.value.flatMap(row=>row.type==='map'?[row.value]:[]):[];}
export function RuntimeChart({node}:{node:ViewNode}){
  const rows=records(node.value).map(row=>({label:row.label?.type==='string'?row.label.value:'',value:row.value?.type==='integer'?row.value.value:'0'})),maximum=rows.reduce((max,row)=>{const value=BigInt(row.value),absolute=value<0n?-value:value;return absolute>max?absolute:max;},1n);
  return <figure className="runtime-chart"><figcaption>{node.text||'Chart'}</figcaption><svg role="img" aria-label={node.text||'Chart'} viewBox={`0 0 400 ${Math.max(40,rows.length*32)}`}><desc>Bars show signed integer proportions. Exact values are in the following table.</desc><line x1="200" y1="0" x2="200" y2={rows.length*32} stroke="currentColor"/>{rows.map((row,index)=>{const value=BigInt(row.value),width=Number((value<0n?-value:value)*170n/maximum);return <g key={index}><rect x={value<0n?200-width:200} y={index*32+4} width={width} height="24" fill="currentColor"/><title>{row.label}: {row.value}</title></g>;})}</svg><div className="runtime-table" role="region" aria-label={`${node.text||'Application'} table`} tabIndex={0} onKeyDown={scrollRegion}><table><caption>{node.text||'Chart'} exact values</caption><thead><tr><th scope="col">Label</th><th scope="col">Value</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}><th scope="row">{row.label}</th><td>{row.value}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No values yet.</p>}</figure>;
}
export function RuntimeCalendar({node}:{node:ViewNode}){
  const fields=node.value?.type==='map'?node.value.value:{},month=fields.month?.type==='date'?fields.month.value:'1900-01-01',[year,number]=month.split('-').map(Number),first=new Date(Date.UTC(year,number-1,1)),offset=first.getUTCDay(),days=new Date(Date.UTC(year,number,0)).getUTCDate(),events=records(fields.events),weeks=Array.from({length:Math.ceil((offset+days)/7)},(_,week)=>week),today=new Date().toISOString().slice(0,10);
  return <div className="runtime-table runtime-calendar" role="region" aria-label={`${node.text||'Application'} calendar`} tabIndex={0} onKeyDown={scrollRegion}><table><caption>{node.text||'Calendar'} · {new Intl.DateTimeFormat('en',{month:'long',year:'numeric',timeZone:'UTC'}).format(first)}</caption><thead><tr>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(day=><th scope="col" key={day}><abbr title={day}>{day.slice(0,3)}</abbr></th>)}</tr></thead><tbody>{weeks.map(week=><tr key={week}>{Array.from({length:7},(_,column)=>{const day=week*7+column-offset+1,date=`${month.slice(0,7)}-${String(day).padStart(2,'0')}`;return <td key={column}>{day>0&&day<=days&&<><time dateTime={date} aria-current={date===today?'date':undefined}>{day}</time>{events.filter(event=>event.date?.type==='date'&&event.date.value===date).map((event,index)=><p key={index}>{event.label?.type==='string'?event.label.value:''}</p>)}</>}</td>;})}</tr>)}</tbody></table></div>;
}
