import assert from 'node:assert/strict';
import {expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {advanceAcceptanceWindow} from './acceptance-clock.mjs';
const require=createRequire(new URL('../apps/web/package.json',import.meta.url)),{default:canonicalize}=await import(require.resolve('canonicalize')),Stripe=require('stripe');
export async function verifyBilling({page,otherPage,context,pool,account,otherAccount,origin,email}){
  assert.equal(await advanceAcceptanceWindow(pool,{account}),true,'Billing fault injection requires a guarded disposable database');
  const window=async()=>{await advanceAcceptanceWindow(pool,{account});await advanceAcceptanceWindow(pool,{account:otherAccount});};
  const headers={Origin:origin,'Content-Type':'application/json'},post=(client,value)=>client.request.post(`${origin}/api/billing`,{headers,data:canonicalize(value)}),summary=async client=>(await(await client.request.get(`${origin}/api/billing`)).json());
  const retry=(worker,reference,client=page)=>client.request.post(`${origin}/api/operations`,{headers,data:canonicalize({action:'retry_worker',worker,reference,expected_attempts:20})});
  const fixture=async(path,body={})=>{const response=await fetch(`${process.env.NEEDWARE_BILLING_API_URL}/fixture/${path}`,{method:'POST',headers:{'Content-Type':'application/json','x-fixture-token':process.env.NEEDWARE_BILLING_FIXTURE_TOKEN},body:JSON.stringify(body)});assert.equal(response.status,200);return response.json();};
  const worker=()=>execFileSync(process.execPath,['scripts/billing-worker.mjs','--once'],{env:process.env,stdio:'inherit',timeout:60000});
  const initial=await summary(page);assert.equal(initial.configured,true);assert.equal(initial.price.amount,2500);assert.equal(initial.price.livemode,false);assert.equal(initial.usage.plan,'free');const price=initial.price;
  const anonymous=await context.browser().newContext();try{assert.equal((await anonymous.request.get(`${origin}/api/billing`)).status(),401);assert.equal((await post({request:anonymous.request},{action:'portal'})).status(),401);}finally{await anonymous.close();}
  assert.equal((await post(otherPage,{action:'portal'})).status(),404);assert.equal((await post(otherPage,{action:'portal',customer:'cus_foreign'})).status(),400);
  assert.equal((await page.request.post(`${origin}/api/billing`,{headers:{...headers,Origin:'https://attacker.invalid'},data:canonicalize({action:'checkout',id:randomUUID(),price,consent:true})})).status(),403);
  assert.equal((await post(page,{action:'checkout',id:randomUUID(),price:{...price,amount:1},consent:true})).status(),409);
  const request={action:'checkout',id:randomUUID(),price,consent:true};await fixture('checkout-failure');assert.equal((await post(page,request)).status(),503);const pending=(await pool.query('SELECT * FROM needware_billing_checkout WHERE account_id=$1',[account])).rows[0];assert.equal(pending.id,request.id);assert.equal(pending.session_id,null);
  await page.goto(`${origin}/billing`);await expect(page.getByRole('heading',{name:'Billing and your plan',exact:true})).toBeVisible();await expect(page.getByText('Stripe test billing. This installation cannot accept a real payment in this mode.',{exact:true})).toBeVisible();await page.reload();assert.equal((await summary(page)).checkout.id,request.id);
  await page.route('https://checkout.stripe.com/**',route=>route.fulfill({contentType:'text/html',body:'<h1>Authored checkout redirect fixture</h1>'}));await page.getByRole('checkbox',{name:/I reviewed/}).check();await page.getByRole('button',{name:'Continue to Stripe checkout',exact:true}).click();await page.waitForURL('https://checkout.stripe.com/**');await expect(page.getByRole('heading',{name:'Authored checkout redirect fixture',exact:true})).toBeVisible();
  const stored=(await pool.query('SELECT * FROM needware_billing_checkout WHERE account_id=$1',[account])).rows[0];assert(stored.session_id);assert.equal(new Date(stored.expires_at).getTime(),new Date(pending.expires_at).getTime());await page.goto(`${origin}/billing`);
  const duplicate=await post(page,request);assert.equal(duplicate.status(),200);assert.equal((await duplicate.json()).url,stored.url);assert.equal((await post(page,{...request,id:randomUUID()})).status(),409);assert.equal((await pool.query('SELECT * FROM needware_billing_checkout WHERE account_id=$1',[account])).rowCount,1);
  const customer=(await pool.query('SELECT customer_id FROM needware_billing_account WHERE account_id=$1',[account])).rows[0].customer_id;assert.equal((await summary(page)).usage.plan,'free','Checkout URL/return does not grant paid access');assert.equal((await post(page,{action:'portal'})).status(),200);
  await pool.query("INSERT INTO needware_account_hold(account_id,active,reason) VALUES($1,true,'spam')",[account]);try{assert.equal((await post(page,request)).status(),403);assert.equal((await post(page,{action:'portal'})).status(),200);assert.equal((await summary(page)).usage.creation_hold,true);}finally{await pool.query('DELETE FROM needware_account_hold WHERE account_id=$1',[account]);}
  const sign=(event,timestamp=Math.floor(Date.now()/1000))=>Stripe.webhooks.generateTestHeaderString({payload:JSON.stringify(event),secret:process.env.STRIPE_WEBHOOK_SECRET,timestamp});
  const event=(type,object,customerId=customer)=>({id:`evt_${randomUUID().replaceAll('-','')}`,object:'event',type,api_version:'2026-09-30.endive',livemode:false,created:Math.floor(Date.now()/1000)-10000,data:{object:{id:object,object:type.startsWith('invoice.')?'invoice':'subscription',...(customerId?{customer:customerId}:{})}}});
  const deliver=(value,signature=sign(value))=>page.request.post(`${origin}/api/billing/webhook`,{headers:{'Content-Type':'application/json','stripe-signature':signature},data:JSON.stringify(value)});
  let references=await fixture('state',{customer,options:{paid:false}});const unpaid=event('invoice.paid',references.invoice);
  assert.equal((await deliver(unpaid,'t=1,v1=forged')).status(),400);assert.equal((await deliver(unpaid,sign(unpaid,Math.floor(Date.now()/1000)-600))).status(),400);assert.equal((await deliver(unpaid,sign(unpaid,Math.floor(Date.now()/1000)+600))).status(),400);assert.equal((await deliver({...unpaid,livemode:true})).status(),400);assert.equal((await deliver({...unpaid,account:'acct_connected'})).status(),400);
  assert.equal((await page.request.post(`${origin}/api/billing/webhook`,{headers:{'Content-Type':'application/json','stripe-signature':sign(unpaid)},data:' '.repeat(256*1024+1)})).status(),413);
  assert.equal((await deliver(unpaid)).status(),200);assert.equal((await deliver(unpaid)).status(),200);assert.equal((await deliver({...unpaid,data:{object:{...unpaid.data.object,id:'in_changed'}}})).status(),409);assert.equal((await pool.query('SELECT id FROM needware_billing_event WHERE id=$1',[unpaid.id])).rowCount,1);worker();assert.equal((await summary(page)).usage.plan,'free');
  references=await fixture('state',{customer});const paid=event('invoice.paid',references.invoice);await window();assert.equal((await deliver(paid)).status(),200);worker();assert.equal((await summary(page)).usage.plan,'pro');assert.equal((await pool.query('SELECT processed_at FROM needware_billing_event WHERE id=$1',[paid.id])).rows[0].processed_at instanceof Date,true);
  await page.reload();await expect(page.getByRole('heading',{name:'Pro',exact:true})).toBeVisible();assert.equal((await deliver(paid)).status(),200);worker();assert.equal((await summary(page)).usage.plan,'pro');
  await pool.query('UPDATE needware_billing_account SET merchant_id=$2 WHERE account_id=$1',[account,'acct_foreign']);assert.equal((await summary(page)).usage.plan,'free');assert.equal((await post(page,{action:'portal'})).status(),409);assert.equal((await post(page,request)).status(),409);await pool.query('UPDATE needware_billing_account SET merchant_id=$2 WHERE account_id=$1',[account,process.env.STRIPE_ACCOUNT_ID]);
  await pool.query('UPDATE needware_billing_account SET livemode=true WHERE account_id=$1',[account]);assert.equal((await summary(page)).usage.plan,'free');assert.equal((await post(page,{action:'portal'})).status(),409);assert.equal((await post(page,request)).status(),409);await pool.query('UPDATE needware_billing_account SET livemode=false WHERE account_id=$1',[account]);assert.equal((await summary(page)).usage.plan,'pro');
  // Neither delivery order nor old snapshot timestamps may resurrect a cancelled subscription.
  await fixture('state',{customer,options:{status:'canceled'}});const cancelled=event('customer.subscription.deleted',references.subscription);assert.equal((await deliver(cancelled)).status(),200);worker();assert.equal((await summary(page)).usage.plan,'free');const old=event('invoice.paid',references.invoice);old.created=paid.created;assert.equal((await deliver(old)).status(),200);worker();assert.equal((await summary(page)).usage.plan,'free');
  for(const options of [{refund:true},{disputed:true},{warning:true},{fraud:true},{wrong_price:true},{wrong_customer:true},{wrong_subscription:true},{quantity:2},{expired:true},{missing_payments:true}]){
    await window();await fixture('state',{customer,options});assert.equal((await deliver(event('invoice.paid',references.invoice))).status(),200);worker();assert.equal((await summary(page)).usage.plan,'free',JSON.stringify(options));
  }
  await window();await fixture('state',{customer,options:{disputed:true,dispute_status:'won'}});assert.equal((await deliver(event('charge.dispute.closed',references.dispute,null))).status(),200);worker();assert.equal((await summary(page)).usage.plan,'pro');
  await pool.query(`UPDATE needware_entitlement SET updated_at=now()-interval '31 minutes' WHERE account_id=$1`,[account]);assert.equal((await summary(page)).usage.plan,'free','Stale verification fails closed');await pool.query(`UPDATE needware_billing_account SET updated_at=now()-interval '16 minutes' WHERE account_id=$1`,[account]);worker();assert.equal((await summary(page)).usage.plan,'pro','Periodic reconciliation repairs missing events');
  // Inject a failed entitlement write: receipt remains queued and both billing/entitlement snapshots roll back.
  await fixture('state',{customer,options:{status:'unpaid'}});const rollback=event('customer.subscription.updated',references.subscription);assert.equal((await deliver(rollback)).status(),200);
  await pool.query(`CREATE FUNCTION reject_entitlement_update() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'Acceptance entitlement failure';END$$;CREATE TRIGGER reject_entitlement_update BEFORE UPDATE ON needware_entitlement FOR EACH ROW EXECUTE FUNCTION reject_entitlement_update()`);
  try{worker();assert.equal((await summary(page)).usage.plan,'pro');assert.equal((await pool.query('SELECT processed_at,failure FROM needware_billing_event WHERE id=$1',[rollback.id])).rows[0].processed_at,null);assert.equal((await pool.query('SELECT status FROM needware_billing_account WHERE account_id=$1',[account])).rows[0].status,'active');}finally{await pool.query('DROP TRIGGER reject_entitlement_update ON needware_entitlement;DROP FUNCTION reject_entitlement_update()');}
  await pool.query('UPDATE needware_billing_event SET attempts=20,merchant_id=$2 WHERE id=$1',[rollback.id,'acct_foreign']);assert.equal((await retry('billing_event',rollback.id)).status(),409);await pool.query('UPDATE needware_billing_event SET merchant_id=$2,livemode=true WHERE id=$1',[rollback.id,process.env.STRIPE_ACCOUNT_ID]);assert.equal((await retry('billing_event',rollback.id)).status(),409);await pool.query('UPDATE needware_billing_event SET livemode=false WHERE id=$1',[rollback.id]);assert.equal((await retry('billing_event',rollback.id,otherPage)).status(),403);assert.equal((await retry('billing_event',rollback.id)).status(),200);worker();assert.equal((await summary(page)).usage.plan,'free');
  // An authenticated account cannot ask to create a portal for someone else's customer.
  await window();const otherCheckout=await post(otherPage,{action:'checkout',id:randomUUID(),price,consent:true});assert.equal(otherCheckout.status(),200);const otherCustomer=(await pool.query('SELECT customer_id FROM needware_billing_account WHERE account_id=$1',[otherAccount])).rows[0].customer_id;assert.notEqual(otherCustomer,customer);await fixture('state',{customer:otherCustomer});
  await fixture('delete-failure');await pool.query('DELETE FROM auth_user WHERE id=$1',[otherAccount]);assert.equal((await pool.query('SELECT customer_id FROM needware_billing_account WHERE account_id=$1',[otherAccount])).rowCount,0);assert.equal((await pool.query('SELECT customer_id FROM needware_billing_cleanup WHERE customer_id=$1',[otherCustomer])).rowCount,1);worker();assert.equal((await pool.query('SELECT finished_at FROM needware_billing_cleanup WHERE customer_id=$1',[otherCustomer])).rows[0].finished_at,null);
  await pool.query('UPDATE needware_billing_cleanup SET attempts=20 WHERE customer_id=$1',[otherCustomer]);assert.equal((await retry('billing_cleanup',otherCustomer)).status(),200);
  await pool.query('UPDATE needware_billing_cleanup SET next_attempt_at=now(),lease_until=now()-interval \'1 second\' WHERE customer_id=$1',[otherCustomer]);worker();assert((await pool.query('SELECT finished_at FROM needware_billing_cleanup WHERE customer_id=$1',[otherCustomer])).rows[0].finished_at);assert((await fixture('stats')).customers.find(value=>value.id===otherCustomer).deleted);
  const snapshot=await pool.query('SELECT * FROM needware_billing_event');assert(!JSON.stringify(snapshot.rows).includes(email));assert(!JSON.stringify(snapshot.rows).includes(process.env.STRIPE_SECRET_KEY));
  await window();await page.goto(`${origin}/account`);await expect(page.getByRole('button',{name:'Sign out everywhere',exact:true})).toBeVisible();
  console.log('PASS Stripe SDK contract billing: approved-price durable checkout/retry/UI/portal, signed bounded webhooks, replay/order/current paid-state, refund/dispute/fraud/expiry/stale denial, atomic retries and durable subscription deletion; no real Stripe/card/payment');
}
