import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {expect} from '@playwright/test';
import {advanceAcceptanceWindow} from './acceptance-clock.mjs';
import {startWorkerHealth} from '../apps/web/lib/worker-health.ts';
import {createGenerationJob,claimGenerationJob,dispatchGenerationJob,finishGenerationJob} from '../apps/web/lib/generation-store.ts';
const require=createRequire(new URL('../apps/web/package.json',import.meta.url)),{default:canonicalize}=await import(require.resolve('canonicalize'));
async function post(page,path,value){return page.evaluate(async({path,body})=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body});return {status:response.status,body:await response.json()};},{path,body:canonicalize(value)});}
export async function verifyOperations({page,otherPage,context,pool,account,otherAccount,origin}){
  const window=async()=>{await advanceAcceptanceWindow(pool,{account});await advanceAcceptanceWindow(pool,{account:otherAccount});};await window();
  execFileSync('cargo',['run','-p','xtask','--','revision-fixture'],{stdio:'inherit'});const source=await readFile('artifacts/revisions/source.need');
  const publication={action:'publish',id:null,expected_version:0,visibility:'public',title:'Operations fixture',summary:'A signed definition for independent abuse review',package:source.toString('base64'),document:null,source:null};
  const published=await post(otherPage,'/api/registry',publication);assert.equal(published.status,200,JSON.stringify(published.body));let entry=published.body.application;
  const privateDocument=await otherPage.evaluate(async()=>{const r=globalThis.__editableRelay,{DurableSyncSession}=await import('/sync-journal.js'),bytes=r.wasm.authored_sync_example(),scope=JSON.stringify({values:[],collections:['habits']}),native=r.vault.start_document(bytes,crypto.randomUUID(),scope,1,true),root=await r.store.load(JSON.parse(r.vault.account_context()).account);root.bytes.fill(0);const journal=await DurableSyncSession.create(r.store.documents,r.vault,bytes,native,{account:JSON.parse(r.vault.account_context()).account,rootGeneration:root.generation,scope,ownerEpoch:1,authority:r.vault.account_authority(),roster:JSON.stringify([JSON.parse(native.membership())])});await r.relay.synchronize(journal);await r.relay.synchronize(journal);const id=JSON.parse(journal.binding()).document.document;await journal.close();return id;});
  const hidden=await post(otherPage,'/api/registry',{...publication,visibility:'private',package:null,document:privateDocument,title:'Private operator-denial fixture'});assert.equal(hidden.status,200);
  const recipient=await otherPage.evaluate(()=>JSON.parse(globalThis.__editableRelay.vault.device_certificate()));
  const anon=await context.browser().newContext();try{
    assert.equal((await anon.request.get(`${origin}/api/operations`)).status(),401);assert.equal((await otherPage.request.get(`${origin}/api/operations`)).status(),403);
    assert.equal((await anon.request.post(`${origin}/api/reports`,{headers:{Origin:origin,'Content-Type':'application/json'},data:canonicalize({entry:entry.id,reason:'privacy'})})).status(),401);
    assert.equal((await page.request.post(`${origin}/api/operations`,{headers:{Origin:'https://evil.invalid','Content-Type':'application/json'},data:'{}'})).status(),403);
    assert.equal((await post(otherPage,'/api/operations',{action:'hide',id:entry.id,expected_version:1,reason:'privacy'})).status,403);
    assert.equal((await post(page,'/api/operations',{action:'hide',id:entry.id,expected_version:1,reason:'privacy',operator:account})).status,400);
    assert.equal((await post(page,'/api/reports',{entry:entry.id,reason:'unknown'})).status,400);
    assert.equal((await post(page,'/api/reports',{entry:hidden.body.application.id,reason:'privacy'})).status,404);assert.equal((await post(page,'/api/operations',{action:'inspect',id:hidden.body.application.id,expected_version:1,reason:'privacy'})).status,404);
    await otherPage.goto(`${origin}/a/${entry.id}`);await expect(otherPage.getByRole('heading',{name:'Operations fixture',exact:true})).toBeVisible();await otherPage.getByLabel('Report reason').selectOption('privacy');await otherPage.getByRole('button',{name:'Send application report',exact:true}).click();await expect(otherPage.getByText('Report received for operator review',{exact:true})).toBeVisible();
    const report=(await post(otherPage,'/api/reports',{entry:entry.id,reason:'privacy'})).body;assert(report.received);assert.equal((await pool.query('SELECT id FROM needware_abuse_report WHERE entry_id=$1',[entry.id])).rowCount,1);
    await page.goto(`${origin}/operations`);await expect(page.getByRole('heading',{name:'Operations',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Hide Operations fixture',exact:true})).toBeVisible();
    const auditFailure=`operations_${crypto.randomUUID().replaceAll('-','')}`;await pool.query(`ALTER TABLE needware_operator_audit ADD CONSTRAINT ${auditFailure} CHECK(action<>'hide') NOT VALID`);try{assert.equal((await post(page,'/api/operations',{action:'hide',id:entry.id,expected_version:1,reason:'privacy'})).status,503);assert.equal((await pool.query('SELECT moderated FROM needware_registry_entry WHERE id=$1',[entry.id])).rows[0].moderated,false);}finally{await pool.query(`ALTER TABLE needware_operator_audit DROP CONSTRAINT ${auditFailure}`);}
    await page.getByRole('button',{name:'Hide Operations fixture',exact:true}).click();await expect(page.getByText('Review recorded',{exact:true})).toBeVisible();entry=(await(await otherPage.request.get(`${origin}/api/registry/${entry.id}`)).json()).application;assert(entry.moderated);assert.equal(Number(entry.version),2);
    assert.equal((await anon.request.get(`${origin}/api/registry/${entry.id}`)).status(),404);assert.equal((await anon.request.get(`${origin}/api/registry/${entry.id}?revision=${entry.current_digest}&download=1`)).status(),404);assert.equal((await page.request.get(`${origin}/api/registry/${entry.id}?download=1`)).status(),404);
    assert(!(await(await anon.request.get(`${origin}/api/registry`)).json()).applications.some(item=>item.id===entry.id));assert.equal((await otherPage.request.get(`${origin}/api/registry/${entry.id}?download=1`)).status(),200);
    const inspect=await post(page,'/api/operations',{action:'inspect',id:entry.id,expected_version:2,reason:'privacy'});assert.equal(inspect.status,200);assert(Buffer.from(inspect.body.definition,'base64').equals(source));
    assert.equal((await post(page,'/api/operations',{action:'restore',id:entry.id,expected_version:1,reason:'privacy'})).status,409);
    const updated=await post(otherPage,'/api/registry',{...publication,id:entry.id,expected_version:2,title:'Updated hidden fixture'});assert.equal(updated.status,200);assert(updated.body.application.moderated);assert.equal((await anon.request.get(`${origin}/api/registry/${entry.id}`)).status(),404);entry=updated.body.application;
    assert.equal((await post(page,'/api/operations',{action:'restore',id:entry.id,expected_version:2,reason:'privacy'})).status,409);assert.equal((await post(page,'/api/operations',{action:'restore',id:entry.id,expected_version:Number(entry.version),reason:'privacy'})).status,200);assert.equal((await anon.request.get(`${origin}/api/registry/${entry.id}?download=1`)).status(),200);
    assert.equal((await post(page,'/api/operations',{action:'review_report',id:report.id,expected_version:0,reason:'spam'})).status,409);assert.equal((await post(page,'/api/operations',{action:'review_report',id:report.id,expected_version:0,reason:'privacy'})).status,200);assert.equal((await post(page,'/api/operations',{action:'review_report',id:report.id,expected_version:0,reason:'privacy'})).status,409);
    const provider={fixture:true,model:'operations-ledger-fixture'};
    const running=await createGenerationJob(pool,otherAccount,crypto.randomUUID(),'Explicit held account fixture',recipient,provider,100),queued=await createGenerationJob(pool,otherAccount,crypto.randomUUID(),'Undispatched fixture',recipient,provider,100),claimed=await claimGenerationJob(pool);assert.equal(claimed.id,running.id);await dispatchGenerationJob(pool,claimed);
    const hold={action:'hold_account',id:otherAccount,expected_version:0,reason:'spam'};assert.equal((await post(otherPage,'/api/operations',hold)).status,403);assert.equal((await post(page,'/api/operations',hold)).status,200);assert.equal((await post(page,'/api/operations',hold)).status,409);
    assert.equal((await pool.query('SELECT state FROM needware_generation_job WHERE id=$1',[running.id])).rows[0].state,'cancel_requested');assert.equal((await post(otherPage,'/api/registry',publication)).status,403);assert.equal((await anon.request.get(`${origin}/api/registry/${entry.id}?download=1`)).status(),404);assert.equal((await otherPage.request.get(`${origin}/api/registry/${entry.id}?download=1`)).status(),200);
    await assert.rejects(createGenerationJob(pool,otherAccount,crypto.randomUUID(),'Blocked fixture',recipient,provider,100),failure=>failure.status===403);await assert.rejects(dispatchGenerationJob(pool,queued),failure=>failure.status===403);assert.equal((await(await otherPage.request.get(`${origin}/api/generation/jobs`)).json()).usage.creation_hold,true);
    assert.equal(await claimGenerationJob(pool),undefined);assert.equal((await pool.query('SELECT failure FROM needware_generation_job WHERE id=$1',[queued.id])).rows[0].failure,'ACCOUNT_HELD');
    await finishGenerationJob(pool,claimed,null,{configured_cost_microusd:20,conservative_cost_microusd:20,input_tokens:1,output_tokens:1,unknown_usage_requests:0},'CANCELLED');const ledger=(await pool.query('SELECT * FROM needware_generation_usage WHERE account_id=$1',[otherAccount])).rows[0];assert.equal(Number(ledger.spent_microusd),20);assert.equal(Number(ledger.reserved_microusd),0);assert.equal(ledger.attempts,2);
    assert.equal((await post(page,'/api/operations',{...hold,action:'release_account',expected_version:1})).status,200);assert.equal((await anon.request.get(`${origin}/api/registry/${entry.id}?download=1`)).status(),200);const recovered=await createGenerationJob(pool,otherAccount,crypto.randomUUID(),'Released fixture',recipient,provider,100);assert.equal((await post(otherPage,`/api/generation/jobs/${recovered.id}`,{action:'cancel'})).status,202);
    const snapshot=await pool.query('SELECT id,"createdAt" FROM auth_session WHERE "userId"=$1',[account]);await pool.query('UPDATE auth_session SET "createdAt"=now()-interval \'16 minutes\' WHERE "userId"=$1',[account]);try{assert.equal((await page.request.get(`${origin}/api/operations`)).status(),403);}finally{for(const item of snapshot.rows)await pool.query('UPDATE auth_session SET "createdAt"=$2 WHERE id=$1',[item.id,item.createdAt]);}
    await window();for(let i=0;i<10;i++){const result=await post(otherPage,'/api/registry',{...publication,title:`Report-bound fixture ${i}`});assert.equal(result.status,200);const reply=await post(otherPage,'/api/reports',{entry:result.body.application.id,reason:'spam'});assert.equal(reply.status,i===9?429:200);}
    const h1=await startWorkerHealth(pool,'generation'),h2=await startWorkerHealth(pool,'generation');try{await h1.stop();const live=await(await page.request.get(`${origin}/api/operations`)).json();assert(live.workers.find(item=>item.worker==='generation').healthy);assert.equal(live.queues.generation_unknown,0);}finally{await h2.stop();}
    await pool.query("UPDATE needware_worker_health SET state='running',updated_at=now()-interval '31 seconds' WHERE worker='generation'");assert.equal((await(await page.request.get(`${origin}/api/operations`)).json()).workers.find(item=>item.worker==='generation').healthy,false);
    await window();const deadLetter=crypto.randomUUID();await pool.query("INSERT INTO needware_email_outbox(id,user_id,recipient,kind,link,attempts,lease_until) VALUES($1,$2,'dead-letter@example.invalid','verify',$3,20,now()+interval '1 minute')",[deadLetter,account,`${origin}/account?fixture-retry=1`]);const retry={action:'retry_worker',worker:'email',reference:deadLetter,expected_attempts:20};
    assert.equal((await post(otherPage,'/api/operations',retry)).status,403);assert.equal((await post(page,'/api/operations',{...retry,worker:'generation'})).status,400);assert.equal((await post(page,'/api/operations',retry)).status,409);await pool.query('UPDATE needware_email_outbox SET lease_until=NULL WHERE id=$1',[deadLetter]);
    const retryFault=`retry_${crypto.randomUUID().replaceAll('-','')}`;await pool.query(`ALTER TABLE needware_operator_audit ADD CONSTRAINT ${retryFault} CHECK(action<>'retry_worker') NOT VALID`);try{assert.equal((await post(page,'/api/operations',retry)).status,503);assert.equal((await pool.query('SELECT attempts FROM needware_email_outbox WHERE id=$1',[deadLetter])).rows[0].attempts,20);}finally{await pool.query(`ALTER TABLE needware_operator_audit DROP CONSTRAINT ${retryFault}`);}
    assert.equal((await post(page,'/api/operations',retry)).status,200);assert.equal((await post(page,'/api/operations',retry)).status,409);assert.equal((await pool.query("SELECT id FROM needware_operator_audit WHERE action='retry_worker'")).rowCount,1);await pool.query('DELETE FROM needware_email_outbox WHERE id=$1',[deadLetter]);
    const audit=(await pool.query('SELECT * FROM needware_operator_audit')).rows;assert(audit.length>=4);assert(audit.every(item=>item.operator_id===account));assert(!JSON.stringify(audit).includes('email'));
    await otherPage.goto(`${origin}/account`);await page.goto(`${origin}/account`);console.log('PASS operations: independently authorized reports, moderation/pinned downloads/owner exports, publisher CAS, audited inspection/atomic rollback, fresh operators, quotas and worker replica/stale health');
  }finally{await anon.close();}
}
