import assert from 'node:assert/strict';
import {expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {advanceAcceptanceWindow} from './acceptance-clock.mjs';
const require=createRequire(new URL('../apps/web/package.json',import.meta.url)),{default:canonicalize}=await import(require.resolve('canonicalize'));
async function post(page,payload){return page.evaluate(async body=>{const response=await fetch('/api/registry',{method:'POST',headers:{'Content-Type':'application/json'},body});return {status:response.status,body:await response.json()};},canonicalize(payload));}
export async function verifyRegistry({page,otherPage,context,pool,account,otherAccount,origin}){
  execFileSync('cargo',['run','-p','xtask','--','revision-fixture'],{stdio:'inherit'});
  const source=await readFile('artifacts/revisions/source.need'),target=await readFile('artifacts/revisions/target.need');
  const window=async()=>{await advanceAcceptanceWindow(pool,{account});await advanceAcceptanceWindow(pool,{account:otherAccount});};
  await window();
  const document=await page.evaluate(async()=>{const r=globalThis.__needwareRelay,{DurableSyncSession}=await import('/sync-journal.js'),bytes=r.wasm.authored_sync_example(),scope=JSON.stringify({values:[],collections:['habits']}),native=r.vault.start_document(bytes,crypto.randomUUID(),scope,1,true),root=await r.store.load(JSON.parse(r.vault.account_context()).account);root.bytes.fill(0);
    const journal=await DurableSyncSession.create(r.store.documents,r.vault,bytes,native,{account:JSON.parse(r.vault.account_context()).account,rootGeneration:root.generation,scope,ownerEpoch:1,authority:r.vault.account_authority(),roster:JSON.stringify([JSON.parse(native.membership())])});await r.relay.synchronize(journal);await r.relay.synchronize(journal);const document=JSON.parse(journal.binding()).document.document;await journal.close();return document;
  });
  const privatePayload={action:'publish',id:null,expected_version:0,visibility:'private',title:'Encrypted private fixture',summary:'Only the owner may discover this entry',document,package:null,source:null};
  await window();const hidden=await post(page,privatePayload);assert.equal(hidden.status,200,JSON.stringify(hidden.body));const privateEntry=hidden.body.application;
  assert.equal((await otherPage.request.get(`${origin}/api/registry/${privateEntry.id}`)).status(),404);
  assert.equal((await page.request.get(`${origin}/api/registry/${privateEntry.id}?download=1`)).status(),404);
  assert.equal((await otherPage.request.get(`${origin}/api/registry`)).status(),200);
  assert(!(await(await otherPage.request.get(`${origin}/api/registry`)).json()).applications.some(item=>item.id===privateEntry.id));
  await window();assert.equal((await post(otherPage,privatePayload)).status,404);
  await page.goto(`${origin}/registry`);await expect(page.getByRole('heading',{name:'Application registry',exact:true})).toBeVisible();
  await page.getByLabel('Application title',{exact:true}).fill('Shared habit fixture');await page.getByLabel('Application summary',{exact:true}).fill('Reviewed signed fixture for registry acceptance');
  await page.getByLabel('Visibility',{exact:true}).selectOption('unlisted');await page.getByLabel('Signed application definition',{exact:true}).setInputFiles('artifacts/revisions/source.need');
  await page.getByRole('checkbox',{name:'I reviewed the definition and selected visibility',exact:true}).check();await page.getByRole('button',{name:'Publish application',exact:true}).click();
  await expect(page.getByText('Application published. Its sharing URL stays the same across revisions.',{exact:true})).toBeVisible();
  const entries=(await(await page.request.get(`${origin}/api/registry`)).json()).applications,entry=entries.find(item=>item.title==='Shared habit fixture');assert(entry);
  assert(!(await(await otherPage.request.get(`${origin}/api/registry`)).json()).applications.some(item=>item.id===entry.id));
  const anonymous=await context.browser().newContext(),visitor=await anonymous.newPage();
  try{
    assert.equal((await visitor.request.get(`${origin}/api/registry/${privateEntry.id}`)).status(),404);
    assert.equal((await visitor.request.post(`${origin}/api/registry`,{headers:{Origin:origin,'Content-Type':'application/json'},data:canonicalize(privatePayload)})).status(),401);
    assert.equal((await visitor.request.get(`${origin}/api/registry/${entry.id}`)).status(),200);
    assert.deepEqual(await(await visitor.request.get(`${origin}/api/registry/${entry.id}?revision=${entry.current_digest}&download=1`)).body(),source);
    await visitor.goto(`${origin}/a/${entry.id}`);await expect(visitor.getByRole('heading',{name:'Shared habit fixture',exact:true})).toBeVisible();
    await visitor.getByRole('link',{name:'Review and open application',exact:true}).click();await expect(visitor.getByRole('heading',{name:'Review Habit tracker',exact:true})).toBeVisible();
    await visitor.getByRole('button',{name:'Trust signer and run application',exact:true}).click();await expect(visitor.frameLocator('iframe').getByLabel('Habit name')).toBeVisible();
    await visitor.frameLocator('iframe').getByLabel('Habit name').fill('Visitor private state');await visitor.frameLocator('iframe').getByRole('button',{name:'Add habit',exact:true}).click();
    await expect(visitor.frameLocator('iframe').getByText('Visitor private state',{exact:true})).toBeVisible();
    await visitor.goto(`${origin}/a/${entry.id}`);await visitor.getByRole('link',{name:'Remix this application',exact:true}).click();
    await expect(visitor.getByRole('region',{name:'Remix source',exact:true})).toBeVisible();await visitor.getByRole('button',{name:'Trust signer and run application',exact:true}).click();
    await expect(visitor.frameLocator('iframe').getByLabel('Habit name')).toBeVisible();await expect(visitor.frameLocator('iframe').getByText('Visitor private state',{exact:true})).toHaveCount(0);
    await window();const update={action:'publish',id:entry.id,expected_version:Number(entry.version),visibility:'public',title:entry.title,summary:entry.summary,document:null,package:source.toString('base64'),source:null};
    assert.equal((await post(otherPage,update)).status,404);assert.equal((await post(page,{...update,expected_version:999})).status,409);
    const published=await post(page,update);assert.equal(published.status,200,JSON.stringify(published.body));let current=published.body.application;
    assert((await(await visitor.request.get(`${origin}/api/registry`)).json()).applications.some(item=>item.id===entry.id));
    const mutated=Buffer.from(source);mutated[mutated.length-1]^=1;assert.equal((await post(page,{...update,id:null,expected_version:0,package:mutated.toString('base64')})).status,400);
    assert.equal((await page.request.post(`${origin}/api/registry`,{headers:{Origin:'https://attacker.invalid','Content-Type':'application/json'},data:canonicalize(update)})).status(),403);
    assert.equal((await page.request.post(`${origin}/api/registry`,{headers:{Origin:origin,'Content-Type':'application/json'},data:'{"action":"publish","action":"delete"}'})).status(),400);
    await window();const trigger=`registry_fail_${crypto.randomUUID().replaceAll('-','')}`;
    await pool.query(`CREATE FUNCTION ${trigger}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id='${entry.id}' AND NEW.current_digest<>OLD.current_digest THEN RAISE EXCEPTION 'acceptance registry publication refused'; END IF; RETURN NEW; END $$`);
    await pool.query(`CREATE TRIGGER ${trigger} BEFORE UPDATE ON needware_registry_entry FOR EACH ROW EXECUTE FUNCTION ${trigger}()`);
    try{assert.equal((await post(page,{...update,expected_version:Number(current.version),package:target.toString('base64')})).status,503);
      const retained=(await pool.query('SELECT current_digest,version FROM needware_registry_entry WHERE id=$1',[entry.id])).rows[0];assert.equal(retained.current_digest,current.current_digest);assert.equal(retained.version,current.version);
      assert.equal((await pool.query('SELECT 1 FROM needware_registry_revision WHERE entry_id=$1',[entry.id])).rowCount,1);
    }finally{await pool.query(`DROP TRIGGER ${trigger} ON needware_registry_entry`);await pool.query(`DROP FUNCTION ${trigger}()`);}
    const next=await post(page,{...update,expected_version:Number(current.version),package:target.toString('base64')});assert.equal(next.status,200,JSON.stringify(next.body));current=next.body.application;assert.equal(current.id,entry.id);assert.notEqual(current.current_digest,entry.current_digest);
    assert.deepEqual(await(await visitor.request.get(`${origin}/api/registry/${entry.id}?revision=${entry.current_digest}&download=1`)).body(),source);
    const remix=await page.evaluate(async source=>{const path='/wasm/needware_wasm.js',wasm=await import(path);await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const bytes=wasm.remix_package(new Uint8Array(source),crypto.randomUUID(),crypto.randomUUID(),true);return Array.from(bytes);},Array.from(source));
    const remixPayload={...update,id:null,expected_version:0,title:'Independent remix fixture',package:Buffer.from(remix).toString('base64'),source:{entry:entry.id,digest:entry.current_digest}};
    const copied=await post(page,remixPayload);assert.equal(copied.status,200,JSON.stringify(copied.body));assert.equal(copied.body.application.source_entry,entry.id);
    assert.equal((await post(page,{...remixPayload,source:{entry:entry.id,digest:current.current_digest}})).status,400);
    assert.equal((await post(page,{...update,expected_version:Number(current.version),visibility:'private',document,package:null})).status,409);
    const deleted=await post(page,{action:'delete',id:entry.id,expected_version:Number(current.version)});assert.equal(deleted.status,200);
    assert.equal((await visitor.request.get(`${origin}/api/registry/${entry.id}`)).status(),404);assert.equal((await pool.query('SELECT 1 FROM needware_registry_revision WHERE entry_id=$1',[entry.id])).rowCount,0);
    assert.equal((await pool.query('SELECT source_entry FROM needware_registry_revision WHERE entry_id=$1',[copied.body.application.id])).rows[0].source_entry,null);
    const lineage=(await pool.query('SELECT source_digest FROM needware_registry_revision WHERE entry_id=$1',[copied.body.application.id])).rows[0];assert.equal(lineage.source_digest,entry.current_digest);
    await pool.query('UPDATE needware_public_limit SET count=120');
    assert.equal((await visitor.request.get(`${origin}/api/registry`,{headers:{'x-forwarded-for':'203.0.113.77','x-needware-auth-ip':'forged','x-vercel-forwarded-for':'203.0.113.78'}})).status(),429);
    await pool.query('UPDATE needware_public_limit SET reset_at=now()-interval \'1 second\'');
    assert.equal((await visitor.request.get(`${origin}/api/registry`)).status(),200);
    await pool.query('UPDATE needware_public_limit SET bytes=33554432');
    assert.equal((await visitor.request.get(`${origin}/api/registry/${copied.body.application.id}?download=1`)).status(),429);
    await pool.query('UPDATE needware_public_limit SET reset_at=now()-interval \'1 second\'');
  }finally{await anonymous.close();}
  await window();await page.goto(`${origin}/account`);await page.evaluate(async document=>{const wasm=await import('/wasm/needware_wasm.js');await wasm.default({module_or_path:'/wasm/needware_wasm_bg.wasm'});const {openVaultStore}=await import('/vault-store.js'),{DocumentRelay}=await import('/relay-client.js'),store=await openVaultStore(),account=(await(await fetch('/api/auth/get-session')).json()).user.id,root=await store.load(account),vault=wasm.BrowserVault.from_local_backup(root.bytes);root.bytes.fill(0);try{await new DocumentRelay(vault).request({action:'delete',document});}finally{vault.free();store.close();}},document);
  assert.equal((await pool.query('SELECT 1 FROM needware_registry_entry WHERE id=$1',[privateEntry.id])).rowCount,0);
  console.log('PASS real registry: native signed verification, private/unlisted/public discovery, cross-owner/auth/CSRF/canonical/CAS boundaries, stable immutable revision links, consumer publish/open/remix, signed lineage and deletion cascades');
}
