'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import canonicalize from 'canonicalize';
import {authClient} from '../../lib/auth-client';
type Report={id:string;entry_id:string;reason:string;title:string;current_digest:string;version:string;moderated:boolean};
type Summary={reports:Report[];audit:{object_id:string;action:string;reason:string;created_at:string}[];workers:{worker:string;healthy:boolean;last_seen:string|null}[];queues:Record<string,number>;holds:{account_id:string;active:boolean;reason:string;version:string}[];dead_letters:{worker:string;reference:string}[]};
export default function OperationsPanel(){const {data:session}=authClient.useSession();return <OperatorDetails key={session?.user.id??'signedout'} account={session?.user.id}/>;}
function OperatorDetails({account}:{account?:string}){
  const [data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[id,setId]=useState(''),[version,setVersion]=useState(''),[reason,setReason]=useState('harmful');
  const [holdAccount,setHoldAccount]=useState(''),[holdVersion,setHoldVersion]=useState('0');
  async function retry(worker:string,reference:string){setBusy(true);setError('');try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:canonicalize({action:'retry_worker',worker,reference,expected_attempts:20}),signal:AbortSignal.timeout(15000)}),value=await response.json();if(!response.ok)throw Error(value.message);setNotice('Retained worker job scheduled; retry audited');await refresh();}catch(failure){setError(String(failure));}finally{setBusy(false);}}
  const refresh=useCallback(async(signal?:AbortSignal)=>{if(!account)return;const response=await fetch('/api/operations',{cache:'no-store',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(15000)]):AbortSignal.timeout(15000)}),value=await response.json();if(!response.ok)throw Error(value.message);signal?.throwIfAborted();setData(value);setError('');},[account]);
  useEffect(()=>{const controller=new AbortController();void refresh(controller.signal).catch(failure=>{if(!controller.signal.aborted){setData(null);setError(String(failure));}});return()=>controller.abort();},[refresh]);
  async function refreshNow(){setBusy(true);try{await refresh();}catch(failure){setData(null);setError(String(failure));}finally{setBusy(false);}}
  async function review(action:'hide'|'restore'|'review_report'|'inspect'|'hold_account'|'release_account',target=id,expected=Number(version),code=reason){setBusy(true);setError('');try{const response=await fetch('/api/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:canonicalize({action,id:target,expected_version:expected,reason:code}),signal:AbortSignal.timeout(15000)}),value=await response.json();if(!response.ok)throw Error(value.message);if(value.definition){const bytes=Uint8Array.from(atob(value.definition),(character:string)=>character.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes]));const link=document.createElement('a');link.href=url;link.download='reviewed-application.need';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Definition downloaded. Import it on Create application to review its signer and permissions before execution.');}else setNotice('Review recorded');await refresh();}catch(failure){setError(String(failure));}finally{setBusy(false);}}
  return <><header><strong>needware /</strong><nav><Link href="/registry">Registry</Link><Link href="/account">Your account</Link></nav></header><main id="main"><h1>Operations</h1><p>Operator access requires a verified allowlisted account and a sign-in from the last 15 minutes.</p>{!account&&<p>Sign in before opening operations.</p>}{account&&<button disabled={busy} onClick={()=>void refreshNow()}>Refresh operations</button>}{error&&<p role="alert">{error}</p>}<p role="status" aria-live="polite">{notice}</p>{data&&<>
    <section aria-label="Worker health"><h2>Worker health</h2>{data.workers.length===0&&<p>No workers have reported.</p>}{data.workers.map(worker=><p key={worker.worker}>{worker.worker}: {worker.healthy?'healthy':'stopped, stale or degraded'} · {worker.last_seen?new Date(worker.last_seen).toLocaleString():'never reported'}</p>)}{Object.entries(data.queues).map(([key,value])=><p key={key}>{key.replaceAll('_',' ')}: {value}</p>)}<p>Unknown provider dispatches require cost review. Never replay a dispatched generation job automatically.</p>{data.dead_letters.map(job=><p key={`${job.worker}:${job.reference}`}>{job.worker} · {job.reference} <button disabled={busy} onClick={()=>{if(window.confirm('Retry this retained job after resolving its worker configuration? Its original identity and expiry stay unchanged.'))void retry(job.worker,job.reference);}}>Retry retained {job.worker} job {job.reference}</button></p>)}</section>
    <section aria-label="Abuse reports"><h2>Abuse reports</h2>{data.reports.length===0&&<p>No open reports.</p>}{data.reports.map(report=><article key={report.id}><h3><Link href={`/a/${report.entry_id}`}>{report.title}</Link></h3><p>{report.reason} · {report.moderated?'hidden':'available'} · revision {report.current_digest}</p><p>Entry {report.entry_id} · version {report.version}</p><button disabled={busy} onClick={()=>{void review(report.moderated?'restore':'hide',report.entry_id,Number(report.version),report.reason);}}>{report.moderated?'Restore':'Hide'} {report.title}</button><button disabled={busy} onClick={()=>{void review('review_report',report.id,0,report.reason);}}>Mark report reviewed for {report.title}</button></article>)}</section>
    <section aria-label="Moderate an application"><h2>Moderate an application</h2><p>Review the current signed definition and entry version before acting. Hiding removes hosted discovery and downloads for other accounts; downloaded copies and the owner’s access remain.</p><label>Application entry ID<input value={id} onChange={event=>setId(event.target.value)} required/></label><label>Reviewed entry version<input type="number" min="1" value={version} onChange={event=>setVersion(event.target.value)} required/></label><label>Review reason<select value={reason} onChange={event=>setReason(event.target.value)}>{['harmful','privacy','spam','copyright'].map(code=><option key={code}>{code}</option>)}</select></label><button disabled={busy||!id||!version} onClick={()=>{void review('hide');}}>Hide reviewed application</button><button disabled={busy||!id||!version} onClick={()=>{void review('restore');}}>Restore reviewed application</button></section>
    <button disabled={busy||!id||!version} onClick={()=>{void review('inspect');}}>Download signed definition for review</button><p>Inspection is audited and excludes encrypted private definitions.</p>
    <section aria-label="Creation holds"><h2>Creation holds</h2><p>Pausing an account hides its shared registry entries, blocks new publication/creation/checkout and requests cancellation of running jobs. Already dispatched provider requests can still incur cost. Existing data, exports, sync, cancellation, billing portal and deletion remain available.</p><label>Reviewed account ID<input value={holdAccount} onChange={event=>setHoldAccount(event.target.value)}/></label><label>Reviewed hold version<input type="number" min="0" value={holdVersion} onChange={event=>setHoldVersion(event.target.value)}/></label><button disabled={busy||!holdAccount||!holdVersion} onClick={()=>{void review('hold_account',holdAccount,Number(holdVersion));}}>Pause reviewed account</button><button disabled={busy||!holdAccount||!holdVersion} onClick={()=>{void review('release_account',holdAccount,Number(holdVersion));}}>Release reviewed account</button>{data.holds.map(hold=><p key={hold.account_id}>{hold.account_id} · {hold.active?'paused':'released'} · {hold.reason} · version {hold.version}</p>)}</section>
    <section aria-label="Operator audit"><h2>Recent audit</h2>{data.audit.map((item,index)=><p key={index}>{item.action} · {item.object_id} · {item.reason} · {new Date(item.created_at).toLocaleString()}</p>)}</section>
  </>}</main></>;
}
