[package]
name = "needware-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
needware-ir = { path = "../needware-ir" }
needware-expr = { path = "../needware-expr" }
needware-validation = { path = "../needware-validation" }
needware-package = { path = "../needware-package" }
needware-capabilities = { path = "../needware-capabilities" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
ts-rs = { version = "12.0.1", features = ["serde-compat"] }
[dev-dependencies]
needware-crypto = { path = "../needware-crypto" }
[lints]
workspace = true
